### ISSUE TITLE
Future enhancement: use Blacklight Range Limit plugin for solr_year

### ISSUE THREAD

**Issue by ewlarson** [BTAA-Geospatial-Data-Project/geoportal#10]
As my time here winds down, I'm going to throw a few things out there for future work by someone other than me :pizza:. 

Blacklight Range Limit used to be a dependency of GeoBlacklight, but was [made optional](https://github.com/geoblacklight/geoblacklight/pull/362). This might be a useful feature to include, especially as we introduce many thousands of historical maps into the portal.

https://github.com/projectblacklight/blacklight_range_limit

How it looks in EarthWorks
![screen shot 2016-07-12 at 1 21 34 pm](https://media.github.umn.edu/user/2145/files/faabc562-4833-11e6-997b-08065f42e48e)

Of course, I'll be long gone :) -- Kevin Dyke

**Comment by KarenMajewicz** [comment]
Adding the Time Period facet (#32) has addressed this as an alternative and we are not looking to add the widget anymore.  If a better one becomes available, we may re-open this.
