### ISSUE TITLE
Explore Multi-Select Faceting for Solr

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/geoportal#101]
This might help users understand how to combine facets better than just the text

Here's an example from the [Scopus](https://www.scopus.com/) search interface
![multiselect](https://user-images.githubusercontent.com/2367677/41614413-0d8ad1b6-73be-11e8-830a-d01348ba40db.png)

**Comment by ewlarson** [comment]
Some investigation notes here: 

* Blacklight Advanced Search Plugin - Provides multi-select facet functionality for an "advanced search" page, but overrides many default stock/search configuration settings. Cannot find another BL adopter using this outside of advanced search.

* Europeana - Blacklight(lite?) / Ruby on Rails application, uses multi-select facet functionality, appears to be done via a [custom search API](https://github.com/europeana/europeana-portal-collections) and [mustache templates](https://github.com/europeana/europeana-styleguide-ruby)

**Comment by ewlarson** [comment]
Also, this would likely be some form of a Blacklight or GeoBlacklight extension of behavior, and something we wouldn't want to do ourselves but within those communities.

**Comment by karenmajewicz** [comment]
GeoBlacklight 2.0 allows multiple selections per facet. Advanced search plugin does as well.
