### ISSUE TITLE
Users can't combine text phrases/terms for text searches

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/geoportal#102]
A user can only enter one text phrase per search.  Is this intentional?

**Comment by ewlarson** [comment]
Can you please share an example? 

The search logic/functionality comes directly from geoblacklight and it's solrconfig. We haven't made any modifications that would break from what they deliver.

**Comment by KarenMajewicz** [comment]
I don't think it's a bug or anything, and it functions the same on other GeoBlacklights.  We just noticed that it tripped up users during tests.

1. Type something in the search box (ex. "Lakes")
2. Type another term in the search box (ex. "Water")

If you write over the word "Lakes" which is retained in the box, the search resets itself.  It's not intuitive to just add words next to the initial entry.  Also, users can't take advantage of the autofill a second time.

**Comment by ewlarson** [comment]
Let's talk about this more tomorrow. The autosuggest behavior is always listening on the search box, but it only makes suggestions when the two words appear in order within a suggestion.

* lakes (suggestions)
* lakes water (no suggestions)
* lakes erie (suggestions)
* lakes erie shoreline (suggestions)
* lakes erie michigan (no suggestions)

It's just very strict about the order of words in suggestion candidates.

**Comment by karenmajewicz** [comment]
Issue mitigated by implementing the Advanced Search plugin #117
