### ISSUE TITLE
Remove "Format" from facet list

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/geoportal#105]
Consider adding it to the metadata list on the item page

**Comment by KarenMajewicz** [comment]
The value in this field is not always accurate for our collections. Filtering for resource and geometry type is more useful than file type, so it is somewhat redundant.

**Comment by KarenMajewicz** [comment]
It is also a single value field, but many of our records contain multiple file types.

**Comment by ewlarson** [comment]
In production with release 1.8.12
