### ISSUE TITLE
Create a custom element and facet for Genre

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/geoportal#106]
Values:
Scanned maps
Geospatial data
Aerial Imagery
Digital maps

----
This list is more realistic to generate by querying the title or description metadata text, and it likely would be more useful than filtering by raster vs. vector.

**Comment by KarenMajewicz** [comment]
Based on LC Genre/Form terms

**Comment by ewlarson** [comment]
Just to clarify. This is the MetadataUpgrade core's b1g_genre_sm field, right?

**Comment by KarenMajewicz** [comment]
Yes, that's the field.  Could you place this below Resource Type?  This will give us too many similar facets on the dev, but I am hoping that we will be able to choose between which ones are both accurate and useful.
