### ISSUE TITLE
July 2018 Blog Post

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/geoportal#107]
# Contributor Spotlight: University of Minnesota
_This post is the first in a monthly series to highlight each Big Ten Academic Alliance university that contributes to the geoportal._

## Overview of Collections

The University of Minnesota has contributed public GIS records from the [Minnesota Geospatial Commons](https://geo.btaa.org/?f[dct_isPartOf_sm][]=Minnesota+Geospatial+Commons), the [Minnesota Legislative Coordinating Commission](https://geo.btaa.org/?f[dct_isPartOf_sm][]=Minnesota+Legislative+Coordinating+Commission+-+Geospatial+Information+(LCC-GIS)), and several [individual counties](https://geo.btaa.org/?f[dct_isPartOf_sm][]=Minnesota+Counties). They have also added many items from the University’s digital repositories, including scanned maps from the J[ohn R. Borchert Map Library](https://geo.btaa.org/?f[dct_isPartOf_sm][]=John+R.+Borchert+Map+Library), GeoTIFFs from the [Polar Geospatial Center](https://geo.btaa.org/?f[dct_isPartOf_sm][]=Polar+Geospatial+Center), research data from the [U of M Digital Conservancy](https://geo.btaa.org/?f[dct_isPartOf_sm][]=University+of+Minnesota+Digital+Conservancy), and hundreds of mixed resources from the [Minnesota Geological Survey](https://geo.btaa.org/?f[dct_isPartOf_sm][]=Minnesota+Geological+Survey).

[<img src="https://user-images.githubusercontent.com/2367677/42527903-8fc6615e-843f-11e8-9d7b-efd020859582.png">](https://geo.btaa.org/catalog/b98a7b39-830a-48ca-84c2-06332aaebbb8)

#### Project Task Force Members: Ryan Mattke, Head, John R. Borchert Library and Melinda Kernik, Spatial Analyst & Curator.

The BTAA Geoportal has proven to be an excellent platform for showing students how to find and work with different types of spatial data. This was demonstrated recently when Madeleine Kerr, a professor in the School of Nursing, worked with the project team at Minnesota to develop activities for a spring semester 2018 online course. With the [tutorial](https://drive.google.com/file/d/160xUWw3EbGnvqtYW_SbYqg2ptiQazkEc/view?usp=sharing), continuing education students gained experience locating and mapping data related to social determinants of public health. They learned how to use common search interface elements to access digitized historical maps - in this case, [a 19th century map of plague outbreaks in Bombay](https://geo.btaa.org/catalog/905c97ea-d2e7-45fa-92e4-5a1edda60679) from the John R. Borchert Map Library Collection. Students also learned how to find, upload, and combine more recent geospatial data related to childhood lead exposure and to visualize it in ArcGIS Online.

[<img src="https://user-images.githubusercontent.com/2367677/42528081-0f89cff2-8440-11e8-944a-cf89f54b196c.png">](https://geo.btaa.org/catalog/905c97ea-d2e7-45fa-92e4-5a1edda60679)

The geoportal has also been a useful tool for advising researchers. For example, a grad student was looking for GIS data for Twin Cities parks, but the relevant records were not showing up in traditional text searches in the state geoportal. Task Force member Ryan Mattke was able to find this for the student by using the map search option in the geoportal combined with "parks" as a keyword. It turned out that St. Paul parks were part of a large Ramsey County administrative boundaries data set, which would have been hard to locate with just text searching.

**Comment by ewlarson** [comment]
Closing; Been live for awhile already:
https://geo.btaa.org/blog/2018/07/08/contributor-spotlight-umn.html
