### ISSUE TITLE
Facet Ordering

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/geoportal#111]
Place
Genre
Subject
Time Period
Year
Collection
Publisher
Creator * name change
Institution
Type

**Comment by ewlarson** [comment]
Wait... is the "Geometry" facet (b1g_geom_type_sm) gone now?

**Comment by karenmajewicz** [comment]
correct.  Still in the metadata & shows icon, but not a facet.

**Comment by karenmajewicz** [comment]
wait, geom_type_sm is still there, but the b1g_geom_type_sm is NOT in the schema anymore

**Comment by ewlarson** [comment]
How does this look? https://geodev.btaa.org/?utf8=%E2%9C%93&search_field=all_fields&q=

Shall I go ahead and collapse the bottom "Type" facet? I think after that, this facet work is complete.

**Comment by karenmajewicz** [comment]
Looks good. It makes sense design wise to collapse Type.

**Comment by ewlarson** [comment]
In production with release 1.8.12
