### ISSUE TITLE
Upgrade to GBL 1.9

### ISSUE THREAD

**Issue by ewlarson** [BTAA-Geospatial-Data-Project/geoportal#112]
Let's get onto the latest GBL official release.

**Comment by karenmajewicz** [comment]
The IIIF downloads don't display quite how I expected. Example: https://geo.btaa.org/catalog/8fad1ec9-9696-4312-8c53-22bd4946ccb3 shows the download TIFF, but the JPEG from IIIF is part of the drop down generated selections. On the dev site (https://geodev.btaa.org/catalog/8fad1ec9-9696-4312-8c53-22bd4946ccb3) the JPEG is called an original format and spelled JPG.

It's the same in Earthworks (https://earthworks.stanford.edu/catalog/8fad1ec9-9696-4312-8c53-22bd4946ccb3), so not a unique issue to us.

**Comment by karenmajewicz** [comment]
I like the new Download panel, but it gets pushed way to the bottom of the screen now (sort of undoing our work for the last release.) Perhaps swap position of Downloads & Tools panels?

**Comment by karenmajewicz** [comment]
Here is a record with an html metadata page: https://geodev.btaa.org/catalog/e04e80bbc3f446fd8f9d2791a764231a_13

The iframe does not display - here is the error Refused to display 'https://www.arcgis.com/sharing/rest/content/items/e04e80bbc3f446fd8f9d2791a764231a/info/metadata/metadata.xml?format=default&output=html' in a frame because it set 'X-Frame-Options' to 'sameorigin'.

**Comment by ewlarson** [comment]
Well... that's a real problem. They're essentially saying no iframes can wrap their content, and that's their choice to make. That page can only be framed if the frame is on the arcgis.com domain (sameorigin).

Unfortunately, there's no (ethical) way around this really. We'll need to not include HTML metadata for items like this one.

**Comment by karenmajewicz** [comment]
OK, thanks for interpreting. Too bad about metadata hosted on the ArcGIS domain.

**Comment by ewlarson** [comment]
Fixed with 1.9.0 release
