### ISSUE TITLE
Add IIIF link to web services tool link

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/geoportal#114]
see [Princeton example](https://maps.princeton.edu/catalog/4bcf807d-06e2-4ad5-bfd9-6248c0b50628) where the IIIIF link is accessible by clicking on the Web Services text.

**Comment by ewlarson** [comment]
Up on geodev:
https://geodev.btaa.org/catalog/f9eb8493-32ab-4ede-8330-9286846eee0d
