### ISSUE TITLE
Explore Advanced Search plugin for Blacklight

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/geoportal#117]
https://github.com/projectblacklight/blacklight_advanced_search

**Comment by karenmajewicz** [comment]
First pass at different facets:

Dropdown fields: Keyword,Place,Publisher/Creator,Collection

Limit fields: Remove Type and use Genre

**Comment by karenmajewicz** [comment]
"Sorry, I don't understand your search" might make more sense if it said something like "0 Results?"

**Comment by karenmajewicz** [comment]
This looks great - all the searches gave results or else the familiar "No results found for your search".  The selected value being displayed on the expanded facets also make it very clear.

**Comment by ewlarson** [comment]
Fixed with 1.9.0 release
