### ISSUE TITLE
Browse related records link is broken

### ISSUE THREAD

**Issue by ewlarson** [BTAA-Geospatial-Data-Project/geoportal#120]
The "Browse all 25 records..." link is broken in GBL 1.9:
https://geodev.btaa.org/catalog/88cc9b19-3294-4da9-9edd-775c81fb1c59

**Comment by ewlarson** [comment]
With GBL 1.9, our related records link is auto-escaping the "dashes" in the identifier and causing the search to fail:
https://geodev.btaa.org/catalog?f%5Bdc_source_sm%5D%5B%5D=88cc9b19%5C-3294%5C-4da9%5C-9edd%5C-775c81fb1c59

On GBL 1.8, the dashes are properly untouched:
https://geo.btaa.org/catalog?f%5Bdc_source_sm%5D%5B%5D=88cc9b19-3294-4da9-9edd-775c81fb1c59

This might be unintended fallout from:
https://github.com/geoblacklight/geoblacklight/pull/631

**Comment by ewlarson** [comment]
@karenmajewicz Do you recall any specific local B1G Geoportal identifiers with reserved characters?

Trying to craft a solution here, but want to make sure it is well tested for us.

**Comment by karenmajewicz** [comment]
I don't believe that any of our records have identifiers with anything but alphanumeric strings with dashes or underscores.

In the dev site, we do have the fixture records for GeoBlacklight, one of which is https://geodev.btaa.org/catalog/uva-Norfolk:police_point Would that work?
