### ISSUE TITLE
September 2018 Blog Post

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/geoportal#123]
# Contributor Spotlight: Michigan State University
_This post is the third in a monthly series to highlight each Big Ten Academic Alliance university that contributes to the geoportal._

### Scanned Maps
MSU Libraries have submitted a collection of antique scanned maps collections (which focus primarily on Michigan, the Great Lakes region, and Africa)   Here are some of the most downloaded items from this collection:

![50740354a1697b151d700f0e8bf9bc88](https://user-images.githubusercontent.com/2367677/45111285-3e6e3780-b10a-11e8-9c39-519b912b6956.jpeg)
[_A map of the acting superintendency of Michigan, Henry Rowe Schoolcraft, 1837_](https://geo.btaa.org/catalog/b32b70ae-430b-480d-9a34-c6ffbd4f55df)

![300-a-1841-300](https://user-images.githubusercontent.com/2367677/45111217-07982180-b10a-11e8-8fd6-935aaf1ca1f5.jpg)
[_Africa, engraved by G.W. Boynton, 1841_](https://geo.btaa.org/catalog/24c98017-bb9d-43e5-982c-ab20e45439ad)

### Geospatial Data
The BTAA Geoportal brings to our user community authoritative geographic files from a variety of sources.  MSU Libraries in particular worked to bring metadata and links to geographic files produced by: 
- Michigan state government
- Oakland County, Michigan
- Southeast Michigan Council of Governments (SEMCOG)

Of the GIS Data offerings, a file of tree diseases and an elevation file for Oakland County are the most viewed items from MSU in the geoportal.  In the future we hope to include records of GIS data for Flint, Michigan, which is a place of high ongoing interest among students and faculty.

![misurvey](https://user-images.githubusercontent.com/2367677/45112157-81c9a580-b10c-11e8-8abd-6826823e7c83.png)

_[Aerial Survey for Forest Health, Michigan, 2000](https://geo.btaa.org/catalog/ad5aa5068b164d759b6d140aad73cfbd_3)_

## Benefits of Participation in the Project
The Geoportal Project allowed us to increase professional collaboration in a variety of ways.   Amanda participated in a geoportal user interface study and provided useful feedback to the geoportal development community. The project has also sparked collaboration within our own institution. By working with in-house metadata specialists we were able to prepare records of our local scanned maps collection.  A new and ongoing collaboration with the MSU Libraries Repository Team will lead to better hosting and description of this collection.

This project has also greatly increased communication between Big Ten libraries which is a positive end unto itself.  We share ideas at every meeting which we can use to improve our own collection management and initiate projects aimed at enriching our own academic and community research.

**Comment by karenmajewicz** [comment]
This needs to be checked by MSU before publishing.

**Comment by ewlarson** [comment]
Thanks! Was waiting for the word.

**Comment by ewlarson** [comment]
Up on geodev for a final proof read:
https://geodev.btaa.org/blog/2018/09/19/contributor-spotlight-msu.html

Ready for production?

**Comment by karenmajewicz** [comment]
We left out a period after the first sentence - after **and Africa)**
Otherwise, it's fine.

**Comment by ewlarson** [comment]
Fixed the missing period and pushed it to production:
https://geo.btaa.org/blog/2018/09/19/contributor-spotlight-msu.html
