### ISSUE TITLE
Open Index Maps not appearing

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/geoportal#125]
The Open Index Maps are not appearing in the geoportal (both prod and dev)

Cornell fixture example: https://geodev.btaa.org/catalog/cornell-ny-aerial-photos-1960s

Stanford example: https://geodev.btaa.org/catalog/stanford-ts545zc6250 -what is currently showing in the preview is the geoserver web service. However, the open index map should override it, as it shows in Earthworks (https://earthworks.stanford.edu/catalog/stanford-ts545zc6250)

**Comment by ewlarson** [comment]
Okay, I believe this is fixed now -- the index_map code wasn't loaded into the Geoportal as I expected. Can we keep an OpenIndexMap example in Solr so I can write some tests against it? This example one works, unless you prefer something less obviously "for testing".

**Comment by karenmajewicz** [comment]
I was planning to leave all the fixture documents in the development site for testing, but not production. (https://geodev.btaa.org/?f%5Bdct_isPartOf_sm%5D%5B%5D=Fixture+Test)

I did, however, add the Stanford open index map record to the production site and would like to keep it there.  (https://geo.btaa.org/catalog/stanford-ts545zc6250). Unfortunately, when you click on the geoserver preview, it generates an error in our portal.

**Comment by ewlarson** [comment]
SO CLEVER! I like it. Yes, please keep the Fixture Tests in dev like that.

How odd. I did run into that behavior with WMS services before. It must be a combination of OpenIndexMaps and GBL version: https://github.com/geoblacklight/geoblacklight/commit/4b77f539e602a211bfba45c7f68a66e172c71dbb

**Comment by ewlarson** [comment]
Fixed with 1.9.0 release
