### ISSUE TITLE
Many ArcGIS Rest services do not load in dev site (version 1.9)

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/geoportal#126]
### These DO NOT load in the dev site(but do in production)
MapServer
- https://geodev.btaa.org/catalog/dab5051ee2e243e3a4a7a6fc9033325d_2
- https://geodev.btaa.org/catalog/da634bb38ffe4fa3b2e6e0391fbf1618_30
- https://geodev.btaa.org/catalog/712c893b4f064506a905ede8d438c66d_0

FeatureServer
- https://geodev.btaa.org/catalog/1219c569d6b346bf878197693063d876_0

### These DO load in the dev site
FeatureServer
- https://geodev.btaa.org/catalog/957280e232a94bb0a5f481b730a9739b_0
- https://geodev.btaa.org/catalog/059240c4135b411eb2aef4af356a485d_0
- https://geodev.btaa.org/catalog/31583d99aef14f62a379964c79227733_0

ImageServer
- https://geodev.btaa.org/catalog/e036a912559a4eada79028774d052734
- https://geodev.btaa.org/catalog/b85e10eb-3e89-45d6-a40d-3815a5fa5851

Screenshot of error:
![error](https://user-images.githubusercontent.com/2367677/46098324-bf5ca400-c189-11e8-908f-919bd9dfc609.png)

**Comment by ewlarson** [comment]
Troubleshooting here: https://github.com/geoblacklight/geoblacklight/issues/715
