### ISSUE TITLE
Move navigation buttons on the Advanced Search Plugin

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/geoportal#131]
"Start Over" should be at the right side.

"Clear Search" should buttonized and moved to the left.

**Comment by ewlarson** [comment]
"Start Over" and "Clear Search" do the exact same thing. I'm going to remove "Start Over" and buttonize "Clear Search". Sound good?

**Comment by karenmajewicz** [comment]
That looks good.
