### ISSUE TITLE
ESRI Viewer: DynamicMapLayer results

### ISSUE THREAD

**Issue by ewlarson** [BTAA-Geospatial-Data-Project/geoportal#133]
Apply temporary localized bug fix for GBL 1.9 DynamicMapLayer query syntax.

**Comment by ewlarson** [comment]
Local fix on dev. Support for these items should be resolved:

* https://geodev.btaa.org/catalog/dab5051ee2e243e3a4a7a6fc9033325d_2
* https://geodev.btaa.org/catalog/da634bb38ffe4fa3b2e6e0391fbf1618_30
* https://geodev.btaa.org/catalog/712c893b4f064506a905ede8d438c66d_0

**Comment by karenmajewicz** [comment]
The fix appears to work for me.

**Comment by ewlarson** [comment]
Fixed with 1.9.0 release
