### ISSUE TITLE
ESRI Viewer: FeatureLayer results

### ISSUE THREAD

**Issue by ewlarson** [BTAA-Geospatial-Data-Project/geoportal#134]
Develop local bug fix for GBL 1.9 FeatureLayer results

**Comment by ewlarson** [comment]
Broken example link:
https://geodev.btaa.org/catalog/1219c569d6b346bf878197693063d876_0

Absolutely related to GeoBlacklight issue:
https://github.com/geoblacklight/geoblacklight/issues/706

**Comment by ewlarson** [comment]
Another example to debug:
https://geodev.btaa.org/catalog/957280e232a94bb0a5f481b730a9739b_0

**Comment by ewlarson** [comment]
@karenmajewicz Ok, I think the nearby function fixes things for us, for both the point based example and the road polygons. It's up on geodev. Have a poke around and see if you can find anything wrong.

**Comment by karenmajewicz** [comment]
This seems to be working. I think that that selector icon is now different. It used to be just a cross; now it switches to a pointer when hovering over a selectable object.  I think that's actually better, but there is a slight inconsistency across different types of services.

**Comment by ewlarson** [comment]
Another version up now that implements Jack's suggestion to base distance off of map zoom level.
https://github.com/BTAA-Geospatial-Data-Project/geoportal/commit/3a6ff181d62ab064395c2415fdcba2b6ec9899c2

Considering this done. Will jump onto the remaining Q3 issues now.

**Comment by ewlarson** [comment]
Related
https://github.com/BTAA-Geospatial-Data-Project/geoportal/issues/134
