### ISSUE TITLE
October 2018 Blog Post

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/geoportal#135]
# Contributor Spotlight: Pennsylvania State University
_This post is part of a monthly series to highlight each Big Ten Academic Alliance university that contributes to the geoportal._

#### Project Task Force Members: Nathan Piekielek, Geospatial Services Librarian; Paige Andrew, Maps Cataloging Librarian and Linda Ballinger, Metadata Strategist

At the start of the BTAA Geoportal project in 2015, the state of Pennsylvania already had a well-developed [geospatial data clearinghouse (PASDA)](http://www.pasda.psu.edu/) and the Penn State University Libraries had already published online [tens of thousands of scanned Sanborn fire insurance maps](https://libraries.psu.edu/about/collections/digital-map-drawer). What we lacked, however, was a user-friendly online interface with which to search for digital cartographic resources geographically, as well as by keyword and topic regardless of their format (i.e., GIS data OR scanned map). We have incorporated both PASDA metadata and Sanborn maps into the Geoportal so that users can discover both of these resources in a single web interface.

Another unique aspect of the Penn State Libraries is that there are multiple map collections managed by multiple units within the Libraries. The BTAA Geoportal provided us with the opportunity to describe, digitize and centralize access to some map collections that were previously “hidden”, and increase the discoverability of other collections that were already scanned, but not yet posted online.

![image1](https://user-images.githubusercontent.com/2367677/46502625-3af3cc00-c7ee-11e8-95a8-f431d1baf5f4.png)
_Penn State provides access to a nearly complete collection of Pennsylvania Sanborn Fire Insurance Maps_

## Overview of Collections Contributed
Penn State has contributed three major collections to the Geoportal with one more in process as of Fall 2018. Collectively, they provide a wealth of cartographic and geographic information about the state of Pennsylvania from the 1700s to the present day. They also provide access to several more rare maps of the world that are housed within the Eberly Family Special Collections Library. The collections are:

- [Pennsylvania Spatial Data Access (PASDA)](http://www.pasda.psu.edu/about.asp) – PASDA is a cooperative project of the Governor’s Office of Administration and Penn State University. It is the state’s official public access open geospatial data portal developed to serve the citizens of the Commonwealth of Pennsylvania.

- [Sanborn Fire Insurance Maps of Pennsylvania](https://libraries.psu.edu/about/collections/sanborn-fire-insurance-maps) – Sanborn maps are very large scale engineering drawings of populated places from the mid-1800s to the mid-1900s. They include detailed information that was used in issuing fire insurance such as building footprints, building construction material type and sometimes the business names or types of building occupants. These maps often provide the most detailed information about populated places of the 1800s and early 1900s.

- Rare maps – over the course of many decades, Penn State’s Special Collections Library amassed a rare book and manuscript collection that included maps and other cartographic materials. Although some of this material had been previously cataloged, going through a scanning process allowed us to upgrade existing bibliographic descriptions for individual maps to current standards, enabling them to be retrieved by their geographic coordinates. Inclusion of these collections in the BTAA Geoportal project represents the first time that this material has been digitized and made freely accessible online for all to use.

- Historic maps of Pennsylvania – in parallel to the rare maps collection, the Special Collections Library also acquired and curated a substantial collection of historic Pennsylvania maps that had not been previously cataloged and digitized. We are in the process of cataloging and digitizing this collection in preparation for posting to the BTAA Geoportal. This should be complete by winter 2018/2019.

![30114](https://user-images.githubusercontent.com/2367677/46765673-36735b80-cca5-11e8-96fe-cc624e3ac8d8.jpg)

[_This 1733 map provides an example of early historical maps of Pennsylvania and the Atlantic Coast housed in the Penn State University Libraries Special Collections unit._](https://geo.btaa.org/catalog/5ed85c65-6566-4f6e-96fb-cfeeb2d3ded2)

The BTAA Geoportal has provided Penn State Libraries the opportunity to centralize online access to a number of digital cartographic resources for the benefit of our user community. What is more, the Geoportal has provided engaged scholarship opportunities for students to learn marketable skills while providing assistance to us and our participation in this exciting project.

**Comment by ewlarson** [comment]
This blog post and all the outstanding Q3 issues are up on geodev now. Please let me know if anything seems amiss, or if you need any changes. If all of these issues are squashed, I'll cut our new release next Tuesday morning. Cheers!

**Comment by karenmajewicz** [comment]
The screenshot of the map was a little clunky. I replaced it with just the map image and put a link to its landing page beneath.

**Comment by ewlarson** [comment]
Updated on geodev. Prepping release to production now.

**Comment by karenmajewicz** [comment]
Minor error in opening paragraph. Instead of "This post is the third in a monthly series..." it can say "This post is part of a monthly series"  (can fix when next blog post goes up)
