### ISSUE TITLE
Check if missing layer_geom_type_s values causes error

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/geoportal#139]
I have some [test records in the dev geoportal for "collections"](https://geodev.btaa.org/?f%5Bdc_type_sm%5D%5B%5D=Collection) that don't have a layer_geom_type_s element. On the search results page, they are fine when using the Map View. However, if I switch to List View, the application throws an error. (`undefined method "downcase" for nil:NilClass`) Is this because they are missing the geometry type?

**Comment by ewlarson** [comment]
I'll take a look!

**Comment by ewlarson** [comment]
Indeed. That view is looking for a layer_geom_type_s value to choose a default icon:
https://github.com/BTAA-Geospatial-Data-Project/geoportal/blob/develop/app/views/catalog/_index_split_default.html.erb#L14-L16

Is that doc field commonly empty? Looks like this code has been in use since April/May this year.

**Comment by karenmajewicz** [comment]
I believe that all the records outside of this test set have a geometry type value. I thought a recent GeoBlacklight version fixed this issue (https://github.com/geoblacklight/geoblacklight/issues/516), but maybe that didn't translate to our List View?  

It's not a pressing issue right now, but we will likely want to include records at some point that do not have a geometry type.

**Comment by ewlarson** [comment]
Yeah, our list view vs. map view is a customization. GBL might have been corrected, but B1G is not... yet.

What icon would you want to represent a non-geom-type entry?

**Comment by ewlarson** [comment]
Close. Resolved via metadata.
