### ISSUE TITLE
Change label for "Ohio" to "Ohio State"

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/geoportal#140]
I made a change in GeoBlacklight icons to call this icon "ohio-state" for clarity. However, I don't know how to trigger the label change in the Geoportal. (Example: https://geodev.btaa.org/catalog/11a-01 vs https://geodev.btaa.org/catalog/ff0af920c18e4aa78459137b6efcd3d3_12)

**Comment by ewlarson** [comment]
We'll need to cut a release of the geoblacklight-icons gem that includes your change, then get the updated gem into the Geoportal.

**Comment by karenmajewicz** [comment]
The metadata is updated to say Ohio State now too, so this can be added to the production site.
