### ISSUE TITLE
WFS Services - Troubleshoot

### ISSUE THREAD

**Issue by ewlarson** [BTAA-Geospatial-Data-Project/geoportal#141]
WFS Test collection:
https://geodev.btaa.org/?f%5Bdc_publisher_sm%5D%5B%5D=Howard+County%2C+Maryland&page=1

Show pages not displaying map:
https://geodev.btaa.org/catalog/b22bce1f-5fe1-4032-9850-2658c8fad2d9

**Comment by karenmajewicz** [comment]
They display if I change the default to WMS, but the attributes don't seem to be queryable.

**Comment by karenmajewicz** [comment]
Additionally, why don't the records for our GeoServer items contain the generated downloads panel?  I thought they used to appear in the dropdown arrow for the [Bloomington records.](https://geodev.btaa.org/?f%5Bdc_type_sm%5D%5B%5D=Service&page=1&q=bloomington+indiana&search_field=all_fields)

**Comment by ewlarson** [comment]
One issue at a time, please :)

**Comment by ewlarson** [comment]
Yeah, those Wms queries are returning empty results: {"values":[]}

We'll need to try and write a query that properly returns results to begin debugging the difference between GeoBlacklight's query and a good query.

**Comment by ewlarson** [comment]
NYU Wms example works in both GBL and B1G.

[Local GeoBlacklight Wms](http://localhost:3000/catalog/nyu-2451-34564) example.

![wms_nyu_geoblacklight](https://user-images.githubusercontent.com/69827/47240498-197a0f00-d3ae-11e8-8716-3f5852ffb617.png)

[Local Geoportal Wms](http://localhost:3001/catalog/nyu-2451-34564) example.

![wms_nyu_geoportal](https://user-images.githubusercontent.com/69827/47240522-272f9480-d3ae-11e8-862c-9332a984c03b.png)

**Comment by karenmajewicz** [comment]
out of scope
