### ISSUE TITLE
GeoServer items - generated downloads panel

### ISSUE THREAD

**Issue by ewlarson** [BTAA-Geospatial-Data-Project/geoportal#142]
_Originally posted by @karenmajewicz in https://github.com/BTAA-Geospatial-Data-Project/geoportal/issues/141#issuecomment-431462784_

**Comment by ewlarson** [comment]
Additionally, why don't the records for our GeoServer items contain the generated downloads panel? I thought they used to appear in the dropdown arrow for the [Bloomington records](https://geodev.btaa.org/?f%5Bdc_type_sm%5D%5B%5D=Service&page=1&q=bloomington+indiana&search_field=all_fields).

**Comment by karenmajewicz** [comment]
Ah, I see.  Adding a WMS is necessary for the web service to display.  But, also adding WFS is necessary for the export panel.  I may have to add this to the GBL Wiki pages.

**Comment by karenmajewicz** [comment]
Items display properly, but when clicking an Export download, an error is generated.

Example: Stanford fixture record: https://geodev.btaa.org/catalog/stanford-cz128vq0535

Howard County record: https://geodev.btaa.org/catalog/19b8151c-451e-458d-862a-fc0be932935d

**Comment by ewlarson** [comment]
Yeah. Looks like a local Geoportal issue for sure. I'll troubleshoot.

**Comment by ewlarson** [comment]
We were missing the tmp directory (tmp/cache/downloads) these files would be downloaded to for downloading. Added the directory to geodev and geoprod and export file downloading is working.

**Comment by ewlarson** [comment]
Closing the issue. Please re-open if you find any additional problems here.
