### ISSUE TITLE
Change name of Tools panel

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/geoportal#145]
This panel includes links that are not "tools." New name TBD.

**Comment by ewlarson** [comment]
Bunch of "Tools" refactoring is up on geodev:
https://geodev.btaa.org/catalog/stanford-cg357zz0321

Renamed panel to "Links", removed email and bookmark, added View Source button, reordered items so it's View Source button, Metadata link, Web services link
