### ISSUE TITLE
Remove Bookmark and Email from Tools panel

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/geoportal#146]
They may still be useful, but take up too much real estate at the top of the Tools panel.

**Comment by ewlarson** [comment]
![screen shot 2018-11-14 at 3 07 29 pm](https://user-images.githubusercontent.com/69827/48512438-15130b80-e81f-11e8-920b-0802595b8d6e.png)

Probably not our desired outcome... will need to see if we can circumvent the "Tools" panel if no tools are to be rendered.

**Comment by karenmajewicz** [comment]
If we insert the More Details Link, there would (nearly) always be something in there. Instead of being called tools, the whole panel should be labeled something else.  Maybe "Links"?

**Comment by karenmajewicz** [comment]
Or, could the title of the box be removed altogether?

**Comment by ewlarson** [comment]
I've got a fix that doesn't display the Tools panel, but I like your idea of adding the "More Details" there. The title can be changed easily. No title might look rather funny...

**Comment by karenmajewicz** [comment]
By the way - I have grouped a few related issues as a "Milestone" to reorganize the layout of the links on the Item Display page. https://github.com/BTAA-Geospatial-Data-Project/geoportal/milestone/9 (doesn't display on the project board).

**Comment by karenmajewicz** [comment]
Should remove Bookmarks from top menu for now as well.
