### ISSUE TITLE
November 2018 blog post

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/geoportal#150]
# Contributor Spotlight: Indiana University Bloomington
_This post is part of a monthly series to highlight each Big Ten Academic Alliance university that contributes to the geoportal._

## Overview of Collections
Indiana University Libraries is contributing records of scanned maps from the [Herman B Wells Library Map Collection](https://libraries.indiana.edu/maps-and-gis) to the Geoportal. The primary focus is on historic maps of Indiana.

![image1](https://user-images.githubusercontent.com/2367677/48143551-a1985980-e274-11e8-92e1-6f2b7c964989.jpg)
_[Colton’s Indiana, 1860](https://geo.btaa.org/catalog/VAC3073-M-00803)_

![image2](https://user-images.githubusercontent.com/2367677/48143605-c5f43600-e274-11e8-8f3b-c0874a66cbd6.jpg)
_[A map of Fort Wayne about 1812: showing also certain earlier happenings](https://geo.btaa.org/catalog/30e5d280-060f-40b3-bd94-232aab738bcf)_

According to [WorldCat](http://www.worldcat.org/), approximately half of the digitized sheet maps in the [Indiana Historic Maps collection](https://geo.btaa.org/?f[b1g_code_s][]=01d-01) have never been cataloged before. A large portion of the state’s earliest maps were issued in the annual reports of the Indiana Geological Survey and, while the bound journals were cataloged and readily findable, the individual maps within were not. We’re very excited to make this hidden collection discoverable in the Geoportal. More sheet maps will be added, so be sure to check back!

## The Geoportal in Action
Theresa loves telling students and faculty members about the Geoportal! As the GIS Librarian, Theresa visits several GIS and mapping classes each semester before students begin work on their final projects. Students of GIS know that finding data is often the most difficult and time-consuming part of a project, so they’re grateful to know that the Geoportal will make their lives easier. The Geoportal has been used as a discovery tool in such classes as Introductory GIS, Food Studies, Mapping Our World, African Studies, Urban Geography, and more!

**Comment by karenmajewicz** [comment]
Updated first paragraph

**Comment by ewlarson** [comment]
This is up on geodev now. If you approve it, I'll push to production:
https://geodev.btaa.org/blog/2018/11/08/contributor-spotlight-iu.html

PSU edit is up there, too:
https://geodev.btaa.org/blog/2018/10/17/contributor-spotlight-psu.html

**Comment by ewlarson** [comment]
Will do!
