### ISSUE TITLE
Consider new layout for Relations tool

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/geoportal#152]
We will be using this more and more soon.  Perhaps they could display across the bottom.

**Comment by karenmajewicz** [comment]
Relations widget displays related items within a collection, but is too far down the right hand column. Consider moving to beneath item metadata.

**Comment by ewlarson** [comment]
Can you please post a URL for an example item? We can use that to work through the design changes.

**Comment by karenmajewicz** [comment]
Here is a collection level record with layers: https://geodev.btaa.org/catalog/05d-07

Here is an atlas with both a parent record and child pages: https://geodev.btaa.org/catalog/9702bb22-4305-4cc2-a8f4-fc10e4ef05df

(still considering how to organize these items and their metadata elements)
