### ISSUE TITLE
December 2018 Blog Post

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/geoportal#157]
# Contributor Spotlight: Ohio State University
_This post is part of a monthly series to highlight each Big Ten Academic Alliance university that contributes to the geoportal._

## Overview of Collections:
Ohio State University joined the BTAA geoportal in the summer of 2017. Our more recent addition as project collaborators means that in some ways we are “playing catch-up” with our peer institutions that have been involved since the project’s inception, but it also gives us a great opportunity to fill in gaps that existed for Ohio maps and geospatial data before we began contributing to the geoportal. 

Our early contributions include geospatial data – [address points, landmarks, and street centerlines](https://geo.btaa.org/?utf8=%E2%9C%93&q=Ohio+Location+Based+Response+System&search_field=all_fields) – associated with the Ohio Geographically Referenced Information Program’s [Location Based Response System (LBRS)](https://ogrip.oit.ohio.gov/projectsinitiatives/lbrs.aspx). Additional data sets now discoverable through the geoportal include open data from [Cuyahoga County](https://geo.btaa.org/?f%5Bdc_publisher_sm%5D%5B%5D=Cuyahoga+County%2C+Ohio), [Franklin County](https://geo.btaa.org/?f%5Bdc_publisher_sm%5D%5B%5D=Franklin+County%2C+Ohio ), the [City of Columbus](https://geo.btaa.org/?f%5Bdc_publisher_sm%5D%5B%5D=City+of+Columbus%2C+Ohio), and the [Mid-Ohio Regional Planning Commission](https://geo.btaa.org/?f%5Bdc_publisher_sm%5D%5B%5D=Mid-Ohio+Regional+Planning+Commission ). To date, Ohio State has contributed more than 800 geospatial data records to the geoportal, and we will continue to work to identify, prioritize, and ingest records to enhance the discoverability of open geospatial data across the state of Ohio.

At Ohio State, our map collections include more than 175,000 geologic, topographic, and thematic maps distributed across our Geology Library, Gardner Family Map Room, Architecture Library, Special Collections, and more. While we have not yet contributed scanned maps to the geoportal, our participation in the project has been of great benefit to us in identifying potential collections for digitization and discussing effective map scanning workflows with our peers. We look forward to contributing scanned maps from our collections in the future.

![osu_fig1](https://user-images.githubusercontent.com/2367677/49393910-96fca300-f700-11e8-8e5e-d52a0a916d1a.JPG)
[_Street Centerlines for Central Ohio, Ohio Location Based Response System_](https://geo.btaa.org/catalog/bfb0c69b7e6d4a3e9efb6ad1a9441212_1 )

## The Geoportal in Action
On November 14, 2018, we celebrated [GIS Day](http://gisday.com/) at Ohio State. Among other activities, this annual event features short “[lightning talks](https://library.osu.edu/researchcommons/wp-content/uploads/2018/11/GISDay2018_AgendaHandout.pdf )” highlighting geospatial research happening across campus and beyond.

One of this year’s lightning talks was an introduction to the BTAA geoportal ([slides available here](https://library.osu.edu/researchcommons/wp-content/uploads/2018/11/GISDay2018_BTAAGeoportal.pdf)) and provided us with an opportunity to raise awareness of this project at Ohio State. Since GIS Day is attended by faculty, staff, and students, as well as GIS professionals affiliated with state and local organizations, this event offered a prime venue for highlighting the geoportal to prospective data users as well as data creators who we may partner with eventual contributions to the geoportal. We look forward to working with both of these groups more in the future!

![osu_fig2](https://user-images.githubusercontent.com/2367677/49393953-b398db00-f700-11e8-8158-64d8bac40bb7.JPG)
_BTAA geoportal presentation during GIS Day 2018 at Ohio State_

**Comment by ewlarson** [comment]
On dev for approval:
https://geodev.btaa.org/blog/2018/12/07/contributor-spotlight-osu.html

**Comment by karenmajewicz** [comment]
Looks good!

**Comment by ewlarson** [comment]
Okok, I'm going to push this out in a release now. Then I'll be working on the remaining homepage things: remove footer, search here button, etc.
