### ISSUE TITLE
Update geoblacklight-icons

### ISSUE THREAD

**Issue by KarenMajewicz** [BTAA-Geospatial-Data-Project/geoportal#16]
I added the Indiana SVG to the GeoBlacklight GitHub repo here: https://github.com/geoblacklight/geoblacklight-icons

**Comment by ewlarson** [comment]
I've got the About page link, the new blog post, and this update to gbl icons on the development server.  Would you please take a look and let me know if we're good to push these changes to production?  Thanks!

**Comment by KarenMajewicz** [comment]
Yes, they all look good to go!

**Comment by ewlarson** [comment]
Cool. We're live with all the changes.
