### ISSUE TITLE
Upgrade to GeoBlacklight 2.0

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/geoportal#163]

**Comment by ewlarson** [comment]
Progress notes here.

- [X] Support BL yarn dependencies
- [ ] Add capistrano-yarn gem
- [ ] Troubleshoot SCSS variable loading
- [ ] BS4 dropped Glyphicon support, determine SVG path forward
- [ ] Homepage styles
- [ ] Search page styles
- [ ] Show page styles

**Comment by ewlarson** [comment]
Closing since we tagged 2.0.0
