### ISSUE TITLE
Update the About page

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/geoportal#166]
Include guidelines for users (see communication plan for more details)

**Comment by ewlarson** [comment]
@karenmajewicz Could you please share the communication plan with me?

**Comment by karenmajewicz** [comment]
Part 1 of fixing the home page is to add links to the institutions names and to replace the map image
 
%ul
%li 1. [University of Illinois at Urbana­-Champaign](https://geo.btaa.org/?f%5Bdct_provenance_s%5D%5B%5D=Illinois)
%li 2. [Indiana University Bloomington](https://geo.btaa.org/?f%5Bdct_provenance_s%5D%5B%5D=Indiana)
%li 3. [University of Iowa](https://geo.btaa.org/?f%5Bdct_provenance_s%5D%5B%5D=Iowa)
%li 4. [University of Maryland](https://geo.btaa.org/?f%5Bdct_provenance_s%5D%5B%5D=Maryland)
%li 5. [University of Michigan](https://geo.btaa.org/?f%5Bdct_provenance_s%5D%5B%5D=Michigan)
%li 6. [Michigan State University](https://geo.btaa.org/?f%5Bdct_provenance_s%5D%5B%5D=Michigan+State)
%li 7. [University of Minnesota (host institution)](https://geo.btaa.org/?f%5Bdct_provenance_s%5D%5B%5D=Minnesota)
%li 8. [Pennsylvania State University](https://geo.btaa.org/?f%5Bdct_provenance_s%5D%5B%5D=Penn+State)
%li 9. [Purdue University](https://geo.btaa.org/?f%5Bdct_provenance_s%5D%5B%5D=Purdue)
%li 10. [University of Wisconsin-­Madison](https://geo.btaa.org/?f%5Bdct_provenance_s%5D%5B%5D=Wisconsin)
%li 11. [Ohio State University](https://geo.btaa.org/?f%5Bdct_provenance_s%5D%5B%5D=Ohio+State)
%li 12. [University of Chicago](https://geo.btaa.org/?f%5Bdct_provenance_s%5D%5B%5D=Chicago)

![002](https://user-images.githubusercontent.com/2367677/55195560-e452c380-517a-11e9-921c-8fe771a5aa5a.png)

**Comment by karenmajewicz** [comment]
Part 2 is to remove the text and list under Sources and replace it with this:

The records in the geoportal have been aggregated from state and local data clearinghouses and university library repositories across the Big Ten region. [Browse by collection here.](https://geo.btaa.org/?f%5Bdc_type_sm%5D%5B%5D=Collection)

**Comment by karenmajewicz** [comment]
Where in the app would this png live?

![map_March2019](https://user-images.githubusercontent.com/2367677/55196795-7f00d180-517e-11e9-8426-ede9e9e6e595.png)
