### ISSUE TITLE
Implement Analytics plan as detailed by Analytics Working Group

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/geoportal#170]

**Comment by ewlarson** [comment]
Added a rake task and cronjob to export Solr to public/data.json nightly
https://github.com/BTAA-Geospatial-Data-Project/geoportal/commit/76fb0b26a0c505ce9bb27bdd56b8ca1494ba4922

@mberkowski Does this seem reasonable to you?
