### ISSUE TITLE
Remove Collection facet

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/geoportal#172]
Collections are now added as parent records and can be accessed under the Type field. The extra Collection facet duplicates terminology and is an artificial grouping, useful only for admin purposes.

**Comment by karenmajewicz** [comment]
Don't need to hide, but do need to rename. Interface Committee will discuss.

**Comment by ewlarson** [comment]
@karenmajewicz Should I still remove this facet? Or is it to be renamed?

**Comment by karenmajewicz** [comment]
remove
