### ISSUE TITLE
Map Location inset doesn't zoom out to world extent

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/geoportal#175]
Only part of Africa is visible for maps with large extents.
Example: https://geo.btaa.org/catalog/f9eb8493-32ab-4ede-8330-9286846eee0d

**Comment by ewlarson** [comment]
This behavior is an artifact of the basemap used to present the map. Using the 'esri' basemap, we only see Africa. But using the 'positron' basemap, we see the map and bbox as expected.

ESRI basemap
<img width="1271" alt="screen shot 2019-02-27 at 11 31 38 am" src="https://user-images.githubusercontent.com/69827/53510384-789a0f80-3a83-11e9-97a9-46686f1e0b08.png">

Positron basemap
<img width="1271" alt="screen shot 2019-02-27 at 11 31 16 am" src="https://user-images.githubusercontent.com/69827/53510404-851e6800-3a83-11e9-9a8c-3cd8c9633872.png">

We can hardcode the sidebar map to use 'positron' always. It's less pretty, but the behavior will be much more accurate for world-sized maps. Let me know what you think!

**Comment by karenmajewicz** [comment]
Let's try the positron basemap. Is that what NYU uses?  A less colorful basemap may work in our favor- sometimes users think the basemap is the resource itself.
