### ISSUE TITLE
Add citation / cite widget

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/geoportal#176]
This is part of Blacklight, and may have been in GeoBlacklight originally.

We are planning to create outreach materials for researchers and realized that this would be a very useful tool.

**Comment by ewlarson** [comment]
Of possible interest,  making citations work in Sufia:
https://bibwild.wordpress.com/2018/04/04/another-round-of-citation-features-in-a-sufia-app/

**Comment by karenmajewicz** [comment]
See this doc for reference: https://docs.google.com/document/d/1dsmchOhRTK4qzMAr3FvYyea1xHtC5r0Tw1xYGDYBTks/edit?usp=sharing

**Comment by karenmajewicz** [comment]
Creator: dc_creator_sm
Date: dct_issued_s
Title: dc_title_s
Publisher: dc_publisher_sm

Identifier: Preference order:
1. value of "http://schema.org/url"
2. value of "http://schema.org/downloadUrl"
3. https://geo.btaa.org/slug
