### ISSUE TITLE
Institution blog post Jan 2019

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/geoportal#178]
# Contributor Spotlight: University of Michigan
_This post is part of a monthly series to highlight each Big Ten Academic Alliance university that contributes to the geoportal._

## Overview of Collections
Our primary contribution to the BTAA Geoportal has been from the digital map collection from the [Stephen S. Clark Library for Maps, Government Information and Data Services](https://www.lib.umich.edu/clark-library). While this digital collection pre-dated the BTAA Geoportal, our involvement in the geoportal has given these maps much more exposure. [Our geographic strengths](https://www.lib.umich.edu/clark-library/collections/maps-atlases) include Michigan and the Great Lakes region, Europe, Japan, and South Africa, and we are continuing to scan and post maps from our collection of over 370,000 paper maps.

![Higo kokusei saikenzu; tsuketari ryakushi; Kashihara Yoshinaga seizu](https://geo.btaa.org/uploads/solr_document_sidecar/image/5476/71996d69-780a-4086-a202-877aef21c2b720180822-63532-rn6w3v.jpeg)
_[Higo kokusei saikenzu: tsuketari ryakushi; Kashihara Yoshinaga seizu](https://geo.btaa.org/catalog/71996d69-780a-4086-a202-877aef21c2b7)_, a Japanese map from 1877.

We have also worked to contribute metadata and links to data from the cities of Detroit and Ann Arbor. Both of these cities have their own portals for providing and finding data. By bringing them together into the BTAA Geoportal, along with the other local government open datasets for which Michigan State University has contributed metadata, our partnership provides a single place where mapmakers and data users can see the open data that Michigan local government has to offer.

![umdetroitsearch](https://user-images.githubusercontent.com/2367677/51923756-3b256200-23b1-11e9-8840-ac4cefb46556.png)
_[Searching for Transportation data from Detroit](https://geodev.btaa.org/?f%5Bdc_publisher_sm%5D%5B%5D=City+of+Detroit%2C+Michigan&f%5Bdc_subject_sm%5D%5B%5D=Transportation&f%5Bdct_provenance_s%5D%5B%5D=Michigan&f3=title&op3=AND&q3=&range%5Bsolr_year_i%5D%5Bbegin%5D=&range%5Bsolr_year_i%5D%5Bend%5D=&search_field=advanced&sort=score+desc%2C+dc_title_sort+asc&view=split)._

## The Geoportal in Action

Besides serving on the project task force, Nicole is on both the Collections and Interface Committees. She also co-chairs the short-term Map Scanning Workflow Working Group. She has really appreciated the opportunity to bring ten plus years of working with patrons on finding geospatial data into a venue where she can collaborate with others in the BTAA to help create better tools for finding data.

One of the challenges in finding geospatial data is the variety of ways in which it is described and represented, and also that each and every portal tends to have a different look and function. Patrons find it hard to know where to start, and there will never be a single portal that will provide a way to discover all the geospatial data that is open and accessible to the world. The BTAA Geoportal provides an ideal place to start a search. As a librarian, data quality and metadata are at the core of what I do, and data literacy is woven into each interaction I have. The BTAA Geoportal supports this process and helps to frame searching for maps and geospatial data, by showing what it looks like to have useful metadata, filters and search features, even when patrons might move their discovery process to other portals.

**Comment by mberkowski** [comment]
@karenmajewicz This post is up on geodev https://geodev.btaa.org/blog/index.html

**Comment by mberkowski** [comment]
Okay, if you just would take one final look at this edit, then I'll publish both with a release.

**Comment by karenmajewicz** [comment]
They look OK to me - go ahead. Thanks!

**Comment by mberkowski** [comment]
Posted to prod.
