### ISSUE TITLE
Blog index and posts not displaying (CSS not loading?)

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/geoportal#179]
The blog index page (https://geo.btaa.org/blog/index.html) and individual blog posts are not displaying correctly - perhaps the CSS is not loading?  It is working for the dev site, but not the production site.

**Comment by ewlarson** [comment]
I'm not sure how this came to be... but there's a whole bunch of CSS rules missing in the prod https://geo.btaa.org/blog/assets/geoportal.css file. Compare that file to the one on dev: https://geodev.btaa.org/blog/assets/geoportal.css

If you want me to fix it, I can find time for that today. Just let me know.

**Comment by karenmajewicz** [comment]
Thanks for checking Eric.  I just noticed this today, even though we published blog posts awhile ago and I thought it was fine at that time (maybe I had a cache in my browser or something).

I did want to point to some blog posts today and next week from Twitter, so if you can fix it that would be great. If it is not a quick fix, it's not the most urgent problem and can wait until you are scheduled again.

**Comment by ewlarson** [comment]
Okay... the repository source code for this CSS file is unchanged from Dec. 2016.
https://github.com/BTAA-Geospatial-Data-Project/geoportal/blob/develop/blog/assets/geoportal.css

Taking a closer look at the file as served from the prod server, it looks corrupted somehow. The file seems to end in the middle of writing out a CSS rule... that's odd.

I think the fix here is to actually redeploy the latest release of the application, or to just hotfix it in place on the prod server -- overwrite that file on place. Jekyll doesn't fingerprint these assets, so just getting the right code up for that file would fix the issue.

@mberkowski - Are you around today? A simple hotfix or redeploy to geoprod should fix one.

**Comment by mberkowski** [comment]
This is weird.  It definitely was working during the prior deploy and I have not logged in there since. I'll try to redeploy now so the assets get recompiled. back in a minute..

**Comment by mberkowski** [comment]
Ah here's a problem: drive partitions are full. Probably we're overrun with logs, which I'll delete...

**Comment by ewlarson** [comment]
I would have thought someone would have seen a Zabbix disk warning?

**Comment by mberkowski** [comment]
Yup. I have to make sure I get those warnings...

**Comment by mberkowski** [comment]
There's 10Gig in public/uploads, total partition is only 32GB.

**Comment by ewlarson** [comment]
Those uploads are map image assets -- mostly from the institutions that do not have IIIF servers in place.

**Comment by mberkowski** [comment]
I have the site redeployed after clearing a tiny bit of space, and I can find a couple more areas to remove stuff. We will put in a request immediately to double the partition size, which should be possible to do without downtime.

**Comment by ewlarson** [comment]
Thanks for the help @mberkowski 

I'd love to move those map images to Amazon S3, which would be possible when we upgrade to GeoBlacklight 2.0 / ActionStorage. That would make scaling these assets easier to deal with, and we could potentially run a local IIIF server like Cantaloupe to standardize the image viewing experience within the application.

If you're looking for a new AWS and Ansible project, this would be pretty fun and rewarding.

**Comment by mberkowski** [comment]
Ok - sufficient space has been regained, zabbix is being corrected, requests have been made to increase partitions for more headroom, and a job to gzip old rotated apache logs is being installed.

**Comment by karenmajewicz** [comment]
Thank you! @mberkowski
