### ISSUE TITLE
Remove spaces from layer_slug_s values

### ISSUE THREAD

**Issue by ewlarson** [BTAA-Geospatial-Data-Project/geoportal#18]
With the Geoblacklight 1.3.0 upgrade branch, I have noticed several 500 errors on asynchronous calls to [fetch item relations](https://geodev.btaa.org/catalog/Penn%20State-urn-1b62c810-5264-49de-bd30-85a67fe87ef2/relations)

All appear to stem from [Solr's inability to handle spaces within our layer_slug_s identifiers](http://127.0.0.1:8983/solr/blacklightcore/select?wt=ruby&fq=%7B%21join+from%3Ddc_source_sm+to%3Dlayer_slug_s%7Dlayer_slug_s%3APenn%20State-urn-4e1d6e11-3baf-433d-93c0-c0546c77f6e4&fl=dc_title_s&fl=layer_slug_s).  For example:
Penn State-urn-1b62c810-5264-49de-bd30-85a67fe87ef2

We should make "friendlier" slugs here, by replacing spaces with dashes and down casing the institution name, too.  

Bad news is this will break a lot of URLs we've exposed to date.  Good news here is that we'll be doing things correctly moving forward.

**Comment by KarenMajewicz** [comment]
Slugs in both the dev and prod site have been updated and are now just the UUID.

**Comment by ewlarson** [comment]
Closing issue, as slugs are fixed in dev and prod.
