### ISSUE TITLE
Upgrade Ruby to 2.6.1

### ISSUE THREAD

**Issue by ewlarson** [BTAA-Geospatial-Data-Project/geoportal#183]
Upgrade Ruby to the latest stable, 2.6.1.

**Comment by mberkowski** [comment]
Successfully tested an upgrade in Vagrant, no downtime there. Server upgrades are scheduled this week.

**Comment by mberkowski** [comment]
Geodev is upgraded and ready for evaluation. Prod scheduled tomorrow.

**Comment by mberkowski** [comment]
In-place upgrades on existing machines cause myriad passenger issues. We'll start by getting to the front of the 2.4x line

**Comment by ewlarson** [comment]
Completed on geodev and geoprod.
