### ISSUE TITLE
Maryland Blog Post

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/geoportal#184]
# Contributor Spotlight: University of Maryland
_This post is part of a monthly series to highlight each Big Ten Academic Alliance university that contributes to the geoportal._

## Overview of Collections

University of Maryland (UMD) Libraries has contributed to the BTAA Geoportal a few dozen scanned historical maps of 18th and 19th century Maryland from our [Maryland Map Collection](https://www.lib.umd.edu/mdmap/?pid=umd:57340) that focuses on the Chesapeake Bay region. Additionally we have helped to identify and contribute nearly [3,000 state and city-wide geospatial datasets](https://geo.btaa.org/catalog?utf8=%E2%9C%93&f1=all_fields&q1=&op2=AND&f2=publisher&q2=&op3=AND&f3=title&q3=&f_inclusive[b1g_genre_sm][]=Aerial+imagery&f_inclusive[b1g_genre_sm][]=Geospatial+data&f_inclusive[dct_provenance_s][]=Maryland&range[solr_year_i][begin]=&range[solr_year_i][end]=&sort=score+desc%2C+dc_title_sort+asc&search_field=advanced&commit=Search) for inclusion in the Geoportal, including open data from Washington, D.C. and Baltimore.

![newmapofvirginia](https://user-images.githubusercontent.com/2367677/53432621-7a4ad100-39b8-11e9-9b27-7de56106e4dd.jpg)
[_A New Map of Virginia, Maryland and the Improved Parts of Pennsylvania and New Jersey, 1719_](https://geo.btaa.org/catalog/61287515-84d0-4cf5-8806-11b9dfd00dc0)

## The Geoportal in Action
We see the BTAA Geoportal project as an ideal way to provide access to what has been digitized while also providing centralized access to a multitude of state and civic geospatial datasets. The Chesapeake Bay region has rich ecological geospatial data, and the ability to bring this data together from multiple data sources provides researchers with a more extensive view of the data.

## Coming Soon
UMD Libraries has only digitized a fraction of our map holdings which include over 350,000 print maps including the U. S. Congressional Serial Set maps and Maryland Map Collection. We plan to soon contribute an additional 200+ scanned foreign maps (representing a small subset of the 25,000+ maps in [this collection](https://www.lib.umd.edu/gov-info-gis/maps-and-gis/mckeldin-map-collection-inventories). Maryland Libraries recently partnered with the vendor EastView Geospatial to have the digitized files fully georeferenced, providing the ability to search and browse for these materials within the Geoportal's mapping application.

**Comment by ewlarson** [comment]
Pushed in the 1.9.7 release.
