### ISSUE TITLE
Featured Item: Map of the Nimrod Glacier

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/geoportal#187]
author: Danny Dotson, The Ohio State University

### [Nimrod Glacier](https://geo.btaa.org/catalog/ANT-REF-MT2503-066)
![nimrod glacier](https://user-images.githubusercontent.com/2367677/53434236-be8ba080-39bb-11e9-9d47-4134abb29d26.jpg)

#### What is this item?
A scan of a 1966 USGS map.
   
#### What geographic region is featured?
Antarctica 
  
#### What BTAA library submitted the item?
University of Minnesota
  
#### Interesting tidbits:
- The glacier is named for [The Nimrod](https://en.wikipedia.org/wiki/Nimrod_(ship)), a ship from the early 1900s British Antarctic Expedition
- The map has a polar stereographic projection
- Map's source was aerial photography
 

#### Where can I find out more?
- [Antarctica NZ Digital Asset Manager: Nimrod Glacier](https://adam.antarcticanz.govt.nz/nodes/view/21558)
- [Scripps Glaciology: Turning around on Nimrod Glacier (video)](https://www.youtube.com/watch?v=dkgb1XdE9PE)
- [The geology of the Nimrod Glacier - Beaumont Bay area](https://gcmd.nasa.gov/search/Titles.do?AutoDisplayTitles=true&subset=amd&entry=K002_1960_1961_NZ_2#titles)
- [Nimrod Glacier (Wikipedia)](https://en.wikipedia.org/wiki/Nimrod_Glacier)
- [Geomorphology and stratigraphy of the nimrod glacier–beaumont bay region, Southern Victoria land, Antarctica](https://doi.org/10.1080/00288306.1963.10422076)

**Comment by ewlarson** [comment]
Pushed in the 1.9.7 release.
