### ISSUE TITLE
U-Spatial URLs not resolving

### ISSUE THREAD

**Issue by ewlarson** [BTAA-Geospatial-Data-Project/geoportal#188]
Seeing a JS error while loading this record:
https://geo.btaa.org/catalog/b98a7b39-830a-48ca-84c2-06332aaebbb8

The associated DynamicMapLayer json data is not being fetched properly:
https://gis.uspatial.umn.edu/arcgis/rest/services/Libraries/MNGeospatialCommons_LandUseTwinCities1958/MapServer?f=json

**Comment by karenmajewicz** [comment]
no longer a service - item was removed from scope of hosted web services for the libraries.
