### ISSUE TITLE
Broken link (URI Analysis) script reporting on old links that had already been removed 

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/geoportal#193]
This appears to be the same behavior as we found last summer where the script is scanning links that we have already removed. (Check our emails from 6/7/18 and 6/8/18) Some of the links it is looking for were removed several months ago.

**Comment by ewlarson** [comment]
The automated task to purge all the old URIs wasn't in place soon enough (by 1am on the 1st of the month) for the scheduled cronjobs to run appropriately. Michael could kick these tasks off manually, or you can wait until it runs correctly (and automatically) next month?

The tasks are all scheduled here:
https://github.com/BTAA-Geospatial-Data-Project/geoportal/blob/develop/config/schedule.rb#L24-L36

**Comment by karenmajewicz** [comment]
Thanks for the update on the purge!  We can wait until next month.
