### ISSUE TITLE
Static map images always displaying with 100% width - bottom gets cut off

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/geoportal#194]
examples:

https://geo.btaa.org/catalog/828a9dd7-1178-4775-8fb4-ef7c7d3161c9
https://geo.btaa.org/catalog/4c223fff-935c-4ba9-bf2a-68e7d2e46f51

Note - IIIF and web services (all have zoom controls) are fine.

**Comment by ewlarson** [comment]
Geoportal 2.0 / GBL 2.0 exhibits this behavior. CSS selector must have changed. Troubleshooting.

**Comment by karenmajewicz** [comment]
This still happens in full view.
