### ISSUE TITLE
Institution blog post Mar 2019

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/geoportal#195]
# Contributor Spotlight: University of Iowa
_This post is part of a monthly series to highlight each Big Ten Academic Alliance university that contributes to the geoportal._

## Overview of Collections:
Our largest contribution by volume comes from two of our digital collections: the [Hixson Plat Map Atlases of Iowa](https://geo.btaa.org/catalog/03d-02) and the [Iowa Counties Historic Atlases](https://geo.btaa.org/catalog/03d-01). By adding these collections to the Big Ten Academic Alliance Geoportal in 2016, University of Iowa was the first institution to contribute a series of scanned historic maps. Both collections predate the BTAA Geospatial Task Force, however we felt that the project would aid in discovery and access of these items. Additionally, many of the township atlases have been georeferenced, providing a service to GIS users that had no platform within our digital library collection. The BTAA Geoportal allowed us to link our original records for the scanned maps with these georeferenced, tiled map services of these county atlases, giving visitors the additional option to download or use these web map services in their research or web development.

![desMoines](https://user-images.githubusercontent.com/2367677/54546310-6966fd00-4971-11e9-8c5f-aed768c9b218.png)
Tiled map service for _[An Illustrated Historical Atlas of Des Moines County, Iowa, 1873](https://geo.btaa.org/catalog/f1b57f24-d474-4493-90e1-d3c25f39b65b)_

**Comment by mberkowski** [comment]
@karenmajewicz  Please review https://geodev.btaa.org/blog/2019/03/19/contributor-spotlight-iowa.html and I can release to prod if it's ok.

**Comment by mberkowski** [comment]
Published
