### ISSUE TITLE
Collection Highlight Mar 2019

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/geoportal#196]
### Featured Collection: [District of Columbia Open Data](https://geo.btaa.org/catalog/04c-01)
_Author: Joshua Sadvari_

There is no shortage of noteworthy, thought-provoking information coming out of Washington, D.C. these days… That’s right! I’m talking about [D.C.’s open geospatial data](https://geo.btaa.org/catalog/04c-01)!

#### What’s in this collection?
Close to 750 geospatial data sets covering themes such as business and economic development, demographics, environment, land use and zoning, public safety and service, transportation, and more! Most data sets can be accessed as web services or downloaded in shapefile (.shp) format for use with a desktop GIS.

#### What BTAA Library submitted the collection?
University of Maryland

#### Interesting tidbits:

- Looking to study neighborhood development and regional growth in the D.C. area? Check out the annual [building permit data sets](https://geo.btaa.org/catalog?utf8=%E2%9C%93&f1=all_fields&q1=washington&op2=AND&f2=all_fields&q2=building+permits&op3=AND&f3=title&q3=&range%5Bsolr_year_i%5D%5Bbegin%5D=&range%5Bsolr_year_i%5D%5Bend%5D=&sort=score+desc%2C+dc_title_sort+asc&search_field=advanced&commit=Search) from 2009 to the present.

- Need to get around town during this year’s AAG Annual Meeting (April 3-7) or UCGIS Symposium (June 10-13)? Skip the taxi, and grab a bike from one of D.C.’s many Capital Bike Share locations.

![capitalBikeShare](https://user-images.githubusercontent.com/2367677/54547207-49383d80-4973-11e9-974d-aad200c1b459.png)

_[Capital Bike Share Locations ](https://geo.btaa.org/?utf8=%E2%9C%93&q=capital+bike+share&search_field=all_fields)_

#### Where can I find out more?

- Browse the full collection of open data sets and check out government apps published with ArcGIS Online (like HistoryQuest DC): [http://opendata.dc.gov/](http://opendata.dc.gov/). 

- Learn more about the University of Maryland Libraries GIS and spatial data services: [https://www.lib.umd.edu/gis](https://www.lib.umd.edu/gis). 

#### Have questions about this collection, the BTAA geoportal, or maps and geospatial data in general? Please don’t hesitate to contact our project team!

_Joshua Sadvari is the Geospatial Information Librarian at The Ohio State University Libraries._

**Comment by mberkowski** [comment]
@karenmajewicz Please review https://geodev.btaa.org/blog/2019/03/19/featured-collection-dc-open-data.html

**Comment by karenmajewicz** [comment]
Looks good to publish!

**Comment by mberkowski** [comment]
Published.
