### ISSUE TITLE
Test Record for Image (Thumbnail) URL

### ISSUE THREAD

**Issue by ewlarson** [BTAA-Geospatial-Data-Project/geoportal#2]
[This record](https://lib-geoblacklightdev.oit.umn.edu/catalog/6158f628-52e6-487f-9bb8-b49598fa1148.json) has an additional value in the dct:references_s field with the URI of http://schema.org/thumbnailUrl.

Here is a [list of the currently accepted Reference URIs ](https://docs.google.com/spreadsheets/d/1P_pk4-y66yl3MC3FmG8xxJZdDhdmLLTEZrVLzYxvxQ0/edit?usp=sharing)from the GeoBlacklight documentation.  I have added the thumbnail to the bottom.

Would it be easier if we re-purposed an unused Dublin Core field for this?  Also, maybe we don't want "thumbnails."  Perhaps a larger image resolution/size would be best for the item entry page?

**Comment by ewlarson** [comment]
FWIW, thumbnail support has been added to Blacklight master:
https://github.com/projectblacklight/blacklight/pull/1622/files#diff-0

**Comment by KarenMajewicz** [comment]
Do you see anything that would conflict with it being incorporated into GeoBlacklight main code too?

**Comment by ewlarson** [comment]
No, it appears very straightforward. Just would need to wait for the formal Blacklight release that includes this new feature.  It's really just looking for a URL in the Solr document, and showing the thumb if that value exists.

**Comment by KarenMajewicz** [comment]
I added https thumbnail URLs for all of the Borchert and Clark library collections to the dev site. (This revealed a few broken links, too that I'll work on.)

**Comment by KarenMajewicz** [comment]
This causes the web services (WMS, WFS) to also not show up in the map inset - instead just the bounding box appears.  Can a filter be set for it to be triggered just with the IIIF service, not all?

**Comment by ewlarson** [comment]
Sorry! I pushed your blog post up to the development server, so any thumbnail work here has momentarily disappeared.  If the blog post is ready to go live, I'll put the thumbnail branch back in place.

**Comment by ewlarson** [comment]
I have the thumbnail branch back on dev.  Can you link to an example where the web services are not showing up?  I'll take a look.
https://geodev.btaa.org/

**Comment by KarenMajewicz** [comment]
I don't believe that any of the web services show.  Here's two examples: https://geo.btaa.org/catalog/1704df50-5a98-478d-a443-79dd32ef286d
https://geodev.btaa.org/catalog/1704df50-5a98-478d-a443-79dd32ef286d

or 
https://geo.btaa.org/catalog/f1b57f24-d474-4493-90e1-d3c25f39b65b
https://geodev.btaa.org/catalog/f1b57f24-d474-4493-90e1-d3c25f39b65b

**Comment by KarenMajewicz** [comment]
All Borchert and Clark Map collections on both dev and prod now have a new element, `thumbnail_path_ss`, that has a thumbnail URL.
