### ISSUE TITLE
Google Analytics only tracking hits on blog

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/geoportal#208]
Since April 1, it Google Analytics is only tracking hits to our blog. Did the analytics ID get removed from the rest of the site somehow?

**Comment by ewlarson** [comment]
Odd. Our analytics is must not be getting picked up in GBL 2.0.

I can take a look on Monday!

**Comment by mberkowski** [comment]
@ewlarson If you open the issue on GH and confirm if my suspicion is right, I can fix it next week without interrupting your scheduling/timing/billing

**Comment by ewlarson** [comment]
Hellos! I’m out of town, but I think your suspicion is correct. Roll that change into production and I bet the stats restart. I can look more at this Monday.

**Comment by mberkowski** [comment]
Fixes committed, pending validation...

**Comment by ewlarson** [comment]
FWIW, I don't have access to Google Analytics anymore. Cody or Karen should be able to confirm.
