### ISSUE TITLE
Highlight/buttonize text for New Search, Back to Search, Start Over 

### ISSUE THREAD

**Issue by ewlarson** [BTAA-Geospatial-Data-Project/geoportal#21]
Emphasize these links via button styling.

**Comment by ewlarson** [comment]
TODO: Swap btn-text class to btn-primary

**Comment by KarenMajewicz** [comment]
For reference, I just came across how UVa has buttonized the terms: http://gis.lib.virginia.edu/catalog/stanford-cg357zz0321

**Comment by ewlarson** [comment]
Have this updated on the development server:
https://geodev.btaa.org/?utf8=%E2%9C%93&q=minnesota

Click on a link in the result set to see the buttons on the show page, too.

If this looks good, I'll cut a release and push to production.

**Comment by KarenMajewicz** [comment]
That's a definite improvement and I think you can push to production!

**Comment by ewlarson** [comment]
Closed with release 1.3.1
