### ISSUE TITLE
Verify Expires headers are correctly applied to static assets

### ISSUE THREAD

**Issue by mberkowski** [BTAA-Geospatial-Data-Project/geoportal#211]
Application .htaccess is configured for optimized caching via mod_expires.  But we need to check that those rules are actually being applied in the current implementation as intended. If not, it will be an ops/deploy issue.

**Comment by ewlarson** [comment]
Not working. Sprocket assets are being served without cache-control or expires headers.

**Comment by mberkowski** [comment]
Thanks for checking. Opening an issue on the server side, and should be easy to fix.
