### ISSUE TITLE
Download Metadata link not working - returns to item page

### ISSUE THREAD

**Issue by ewlarson** [BTAA-Geospatial-Data-Project/geoportal#214]

**Comment by ewlarson** [comment]
Example record: https://geo.btaa.org/catalog/92225194-f308-4449-8438-5a1e964d5bef

**Comment by karenmajewicz** [comment]
Should be solved in GeoBlacklight 2.1

**Comment by ewlarson** [comment]
GBL 2.0 isn't firing the GeoBlacklight.metadataDownloadButton(element, i) event. Fixed in this commit:
https://github.com/geoblacklight/geoblacklight/commit/02759d9237964645ffb94ee14b9b83c47ce20e9b
