### ISSUE TITLE
Improve index map layout

### ISSUE THREAD

**Issue by ewlarson** [BTAA-Geospatial-Data-Project/geoportal#216]

**Comment by karenmajewicz** [comment]
Here is an example of an index map: https://geodev.btaa.org/catalog/414ade45-bef0-47ae-98a6-2b883c2642dd

When a user selectes a green polygon in the map view, a thumbnail preview with a few metadata fields appears below the map.  This layout is a little awkward as the user needs to scroll down to see the different items as they are selected.

We probably also need to add some text explaining how the index map works.

**Comment by karenmajewicz** [comment]
https://btaagdp.org/help/indexmaps

links to a basic help page
