### ISSUE TITLE
Connect geoportal to Google Site through links in text or menu

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/geoportal#219]
btaagdp.org/about

btaagdp.org/news

btaagdp.org/help

**Comment by ewlarson** [comment]
@karenmajewicz Where would you like the lowest footer section, with "Hosted by..." and "Policies" links to land?

Currently, these links point to /about#hosting, but with "About" moving to Google Sites, is there a replica of this text over there?

**Comment by karenmajewicz** [comment]
We have this footer on every page of the Google Site:

The technical infrastructure for the project is provided by the University of Minnesota Libraries Web Development department. 
[Privacy Statement](https://www.lib.umn.edu/about/privacy) | [Acceptable Use of IT Resources](http://policy.umn.edu/it/itresources)

Could that be the footer for the geoportal too?
