### ISSUE TITLE
Enhancement: support multi-word synonyms

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/geoportal#22]
There are two files[ in this folder for synonym groups.](https://drive.google.com/drive/folders/0Byl0jXcFUSJ-c1dWRmNBVWZ6UDA?usp=sharing)  (State Synonyms and Task Force Collected Synonyms.)  We would like to add them to Solr.  

- There is some crossover duplication between the lists, but I was hesitant to combine them.  Let me know if this would this create a problem.

- The Task Force collected list contains punctuation in the form of periods.  Is this useful or does Solr ignore periods in searches?

**Comment by ewlarson** [comment]
These synonym files have been added to production.  BUT, it appears properly handling multi-word synonyms isn't easy:
http://opensourceconnections.com/blog/2016/06/23/solr-multi-word-synonym-solutions-2016/

We should ask around the BL community to see if anyone has a preferred solution.

**Comment by ewlarson** [comment]
Bookmarking a potential solution:
http://opensourceconnections.com/blog/2017/01/23/our-solution-to-solr-multiterm-synonyms/

**Comment by ewlarson** [comment]
Another option, after Solr is upgraded in production:
https://lucidworks.com/2017/04/18/multi-word-synonyms-solr-adds-query-time-support/

**Comment by karenmajewicz** [comment]
Closing, as we are moving away from synonyms.
