### ISSUE TITLE
"Read More" for long descriptions not hiding text

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/geoportal#224]
Long descriptions usually are truncated with a Read More link underneath. They are currently not being truncated and spill over metadata. Examples:

https://geodev.btaa.org/catalog/2eddde2f-c222-41ca-bd07-2fd74a21f4de
https://geodev.btaa.org/catalog/00dbc319-4120-4fc6-ba74-4e809385a169

Probably a jQuery bug, as this behavior is only in geodev right now.

**Comment by ewlarson** [comment]
Same issue here: https://github.com/jedfoster/Readmore.js/issues/177

Will try 3.0.0-beta branch
