### ISSUE TITLE
Create descriptions for each type of web service that displays in map preview.

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/geoportal#232]

**Comment by karenmajewicz** [comment]
[Here is a sheet with URIs, titles, and text for rollover help information](https://docs.google.com/spreadsheets/d/1gymulePppsWtak24aBydgn2mAQifMfPOijK6hJSj3gM/edit?usp=sharing)

**Comment by karenmajewicz** [comment]
All "More info" type links could go to this page: https://btaagdp.org/help/web-services

**Comment by ewlarson** [comment]
We're missing one map/viewer type, which is "download" -- these are locally cached, static images from Indiana, PSU, etc. The non-IIIF map images in the Geoportal.

**Comment by karenmajewicz** [comment]
Hmm, not sure what to say about the static images, as they are not web services the way the rest are. Is type "download" the best way to describe them?

**Comment by ewlarson** [comment]
The term "download" is just the word I used to describe them, because the images come from the http://schema.org/downloadUrl value. Maybe they don't need anything, but it feels odd to have one unlike all the others...

Also! Can you point me to a Geoportal entry that renders the map via Web Feature Service (WFS). I don't have one in my local test fixtures, so I'll need to add one.

**Comment by karenmajewicz** [comment]
I know a lot come from the schema.org/downloadUrl value, but I think of them as more often from b1g_image_ss I will add a line to the spreadsheet and share it for those.

We have so few OGC web services that I don't understand how they interact in GBL fully. I _think_ that the map preview actually only displays WMS. If WFS is added, that enables a generated download? So, maybe a WFS label is not needed here.

**Comment by ewlarson** [comment]
Yeah, reading thru the code, "I think that the map preview actually only displays WMS", is indeed correct.

**Comment by karenmajewicz** [comment]
Just verified. Here is what happens when we have something from GeoServer:

https://geodev.btaa.org/catalog/no-wfs (WMS displays, but there is no export option)
https://geodev.btaa.org/catalog/no-wms (nothing displays, but the WFS web service is available from the Web Service link)

**Comment by karenmajewicz** [comment]
I updated the [spreadsheet](https://docs.google.com/spreadsheets/d/1gymulePppsWtak24aBydgn2mAQifMfPOijK6hJSj3gM/edit?usp=sharing) Still undecided on Static Image description, so feel free to edit.
