### ISSUE TITLE
Investigate multipage viewer for atlases

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/geoportal#234]
Examples to try:

Kittson County, MN

- https://geodev.btaa.org/catalog/62aac6a8-d31e-4364-8946-ff9bebbf4a25
- https://umedia.lib.umn.edu/item/p16022coll231:2045

Emmet County, IA

- https://geodev.btaa.org/catalog/30972c42-36ea-44af-9950-6538d7a38867
- https://digital.lib.uiowa.edu/cdm/ref/collection/atlases/id/681

**Comment by karenmajewicz** [comment]
related to #168

**Comment by ewlarson** [comment]
Spent a great deal of the afternoon working to generate a IIIF Manifest for the Kittson County Atlas, via the JSON file UMedia creates. [Here's a look at it in Universal Viewer](http://universalviewer.io/uv.html?manifest=https://gist.githubusercontent.com/ewlarson/d32a03f9f032aba9a6f5e07937813eaf/raw/596609f3e8c61325793b19ec10a867ca4f5bfd98/manifest.json#?c=0&m=0&s=0&cv=0&xywh=-3519%2C-329%2C12176%2C6562)

Screenshot
<img width="1280" alt="Screen Shot 2019-06-25 at 5 10 57 PM" src="https://user-images.githubusercontent.com/69827/60137346-3ef4bf00-976c-11e9-9125-d66991891b64.png">

**Comment by karenmajewicz** [comment]
Looks nice! 

Umedia needs better titles for the pages; not sure if they can do that.

**Comment by ewlarson** [comment]
Progress screenshot

<img width="1280" alt="Screen Shot 2019-06-26 at 4 25 46 PM" src="https://user-images.githubusercontent.com/69827/60216257-2d282000-982f-11e9-93a8-66242935edac.png">

Added a iiif_manifest method to GBL's ItemViewer. If a Solr document has a http://iiif.io/api/presentation#manifest dct_references_s entry, like so:

```json
"dct_references_s":"{\"http://schema.org/url\":\"http://purl.umn.edu/193089\",\"http://iiif.io/api/presentation#manifest\":\"https://gist.githubusercontent.com/ewlarson/d32a03f9f032aba9a6f5e07937813eaf/raw/596609f3e8c61325793b19ec10a867ca4f5bfd98/manifest.json\"}
```

That file will run the iiif_manifest.js javascript file for the viewer, which kicks off mirador and pulls the manifest down.

**Comment by ewlarson** [comment]
Closing with Mirador 3 in production
