### ISSUE TITLE
Troubleshoot IndexMap JS errors

### ISSUE THREAD

**Issue by ewlarson** [BTAA-Geospatial-Data-Project/geoportal#237]
https://geo.btaa.org/catalog/9702bb22-4305-4cc2-a8f4-fc10e4ef05df

**Comment by karenmajewicz** [comment]
https://geo.btaa.org/catalog/491dd450-b802-47a3-b415-0b38c8502104

**Comment by ewlarson** [comment]
Missing a JS behavior?
Uncaught TypeError: GeoBlacklight.Util.indexMapDownloadTemplate is not a function

**Comment by ewlarson** [comment]
See Cornell's implementation:
https://cugir.library.cornell.edu/catalog/cugir-008186
