### ISSUE TITLE
Blog post #6

### ISSUE THREAD

**Issue by KarenMajewicz** [BTAA-Geospatial-Data-Project/geoportal#24]
# Springtime News

## More scanned maps
During March 2017, 802 scanned maps from the University of Michigan Clark Library were added to the geoportal.  Several hundred scanned maps from the University of Minnesota's Borchert Map Library were also added bringing the [total number of map records to over 1700.](https://geo.btaa.org/?f%5Blayer_geom_type_s%5D%5B%5D=Paper+Map)

![clark1ic_39015091186810_full_1908_948__0_native](https://cloud.githubusercontent.com/assets/2367677/24633862/5786ec62-1890-11e7-9e05-bd9f911561ea.jpg)
[A new pocket plan of the cities of London & Westminster with the borough of Southwark, comprehending the new buildings and other alterations to the year 1790.](https://geo.btaa.org/catalog/befb25e9-1e60-451a-9b25-901cb51e04b3)

## Wisconsin orthophotos
Wisconsin contributed new state records, including annual orthophotos National Agriculture Imagery Program sets from the past decade and two sets from the Wisconsin Regional Orthoimagery Consortium.

![dane](https://cloud.githubusercontent.com/assets/2367677/24633875/65a06210-1890-11e7-870e-c03edafbf638.jpg)

[NAIP Imagery, Dane County, Wisconsin, 2004](https://geo.btaa.org/catalog/F49B9BD7-CB8E-4C24-ABC3-BD8E20FACB4C)

## Association of College & Research Libraries Conference
Two Big Ten Academic Alliance Task Force members, Ryan Mattke and Mara Blake, attended the Association of College & Research Libraries Conference during March 2017 and displayed a poster titled, "Lessons in Collaboration: Building a Multi-Institution Geospatial Data Discovery Portal," shown below.  [Check out other posters and presentations on the project website Activities page.  ](https://sites.google.com/umn.edu/btaa-gdp/activities)

![btaa_poster_acrl2017](https://cloud.githubusercontent.com/assets/2367677/24633614/113ca720-188f-11e7-865a-ad089cead9b0.jpg)

**Comment by KarenMajewicz** [comment]
Hi @ewlarson & @mberkowski. Here's another blog post.  No time constraint on post date - just whenever you have time this month.  Thanks!

**Comment by ewlarson** [comment]
I'm on it!

**Comment by ewlarson** [comment]
@KarenMajewicz 

The blog post is live on the development server here:
https://geodev.btaa.org/blog/2017/04/04/springtime-news.html

If you need any changes let me know.  If you want me to push this to production, just say the word!

**Comment by KarenMajewicz** [comment]
I forgot the period at the end of the sentence under Wisconsin Orthophotos after the word Consortium.  Otherwise, looks OK.  Thanks.

**Comment by ewlarson** [comment]
Closed!
