### ISSUE TITLE
Troubleshoot non-displaying Mirador viewer for some items

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/geoportal#240]
About half of the IIIF manifests added display fine. However, many start to load, but then Mirador switches to a blank box.

Example:  https://geo.btaa.org/catalog/e1ec54e6-8bb4-496a-93f9-43ac901bea74

When I load this manifest into the Mirador demo (https://mirador-dev.netlify.com/__tests__/integration/mirador/), it displays perfectly.  Haven't been able to figure out why it doesn't display in the geoportal -developer console doesn't show any errors.

**Comment by ewlarson** [comment]
This one is a mystery to me; I don't work with React/Redux much at all. Here's what I know, but I think we'll need to reach out to the Mirador community for some more assistance.

I installed the React and Redux dev tools. No JS errors are printing in the console, but these tools offer a bit more insight. For example, the Redux debugger shows that nothing appears to happen after the "RECEIVE_MANIFEST" step. We're just left with the the white box.

<img width="633" alt="Screen Shot 2019-08-01 at 9 08 15 AM" src="https://user-images.githubusercontent.com/69827/62300241-0ebfd080-b43c-11e9-8259-408326a72547.png">

When things are working properly, at least one "RECEIVE_INFO_RESPONSE" and a final "UPDATE_VIEWPORT" step should occur.

<img width="633" alt="Screen Shot 2019-08-01 at 9 10 30 AM" src="https://user-images.githubusercontent.com/69827/62300534-9c032500-b43c-11e9-991a-cc5e66678ce9.png">

Our problematic [IIIF Manifest](https://raw.githubusercontent.com/BTAA-Geospatial-Data-Project/iiif-manifests/master/manifest_e1ec54e6-8bb4-496a-93f9-43ac901bea74.json) works in both [UniversalViewer](http://universalviewer.io/uv.html?manifest=https://raw.githubusercontent.com/BTAA-Geospatial-Data-Project/iiif-manifests/master/manifest_e1ec54e6-8bb4-496a-93f9-43ac901bea74.json#?c=0&m=0&s=0&cv=0&xywh=-4484%2C-467%2C18219%2C9329) and the stand-alone [Mirador 3 preview](https://mirador-dev.netlify.com/__tests__/integration/mirador/). It also passes the [IIIF Manifest validator](https://iiif.io/api/presentation/validator/service/).

![Screen Shot 2019-08-01 at 9 18 10 AM](https://user-images.githubusercontent.com/69827/62301025-6b6fbb00-b43d-11e9-89e3-0bc8e53890e7.png)

I'll see if someone from Mirador can offer any insight now.

**Comment by ewlarson** [comment]
Sought help from @mejackreed and he isolated the issue using Mirador's debug build.

[Our Mirador config](https://github.com/BTAA-Geospatial-Data-Project/geoportal/blob/a03fdf91ed968167878ad0fec0cc07121768906e/app/assets/javascripts/geoblacklight/viewers/iiif_manifest.js#L21) is currently setting a canvasIndex value of 2. [Our IIIF Manifest](https://raw.githubusercontent.com/BTAA-Geospatial-Data-Project/iiif-manifests/master/manifest_e1ec54e6-8bb4-496a-93f9-43ac901bea74.json) only has two two images: Map front (0), Map back (1).

With our configuration, Mirador is trying to be helpful and set the current item at index 2, but we only have 0 and 1, so it fails to find 2 and breaks.

Removing the canvasIndex setting fixes the issue. I'll prep a release with this fix now. And, I'll open a bug in the Mirador project so they can consider helping out other people who misconfigure their settings like us.
