### ISSUE TITLE
Disable Cite widget for Type: Collection

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/geoportal#251]
Citations don't work very well for Collections, which don't typically have a Creator or Dates. Could we just disable the widget for items that are dc_type_sm:"Collection"?

**Comment by ewlarson** [comment]
Added a "collection" citation format.

**Comment by karenmajewicz** [comment]
This feature is not on dev yet.

**Comment by ewlarson** [comment]
It should be on geodev... here are the lines of code that would manipulate the citation for collection items:

https://github.com/BTAA-Geospatial-Data-Project/geoportal/blob/develop/app/views/catalog/_citation.html.erb#L9-L22

I don't have an example off-hand. Is it not working properly?

**Comment by ewlarson** [comment]
@karenmajewicz 

The Wabash River Historical Maps and Imagery doc works as expected, right?
https://geodev.btaa.org/catalog/09d-01

**Comment by karenmajewicz** [comment]
Oh, okay- that works. I forgot and thought we were completely disabling the Cite widget for Collections. Now I see that it is just simplified, so it looks good.
