### ISSUE TITLE
Enable/troubleshoot harvesting of new thumbnails from field b1g_image_ss

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/geoportal#254]
Added a few thumbnail links recently that didn't harvest. Ex. https://geo.btaa.org/?utf8=%E2%9C%93&search_field=all_fields&q=Illinois+EPA+Open+Data

**Comment by ewlarson** [comment]
Okay! Thanks for the example. 

Looks like the our b1g_images_ss field isn't short-circuiting the thumbnail harvesting logic here. The fix will likely need to be written in GeoBlacklight Sidecar Images plugin, not the Geoportal.

I'll troubleshoot in that repo.

**Comment by ewlarson** [comment]
Related https://github.com/geoblacklight/geoblacklight_sidecar_images/issues/13

**Comment by ewlarson** [comment]
Fix is to have GBLSCI service_url return nil if a custom image field value is present. Here's what it looks like locally when the Illinois EPA logo is harvested.

<img width="880" alt="Screen Shot 2019-10-22 at 1 49 17 PM" src="https://user-images.githubusercontent.com/69827/67319937-35d5ed80-f4d3-11e9-96b7-16b3c7cd136b.png">
