### ISSUE TITLE
Citation fail - malformed date published value

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/geoportal#258]
This record breaks the Cite tool: https://geodev.btaa.org/catalog/b06d96e4-c917-4afc-a3df-adbbc9a2273c

When clicking the widget, a popup shows "Network Error." Error in email report showed:
undefined method `to_date' for nil:NilClass.

Date published field has error value of "2004-01-00".

I can fix the metadata, but we may want to have another error handler to guard against malformed dates.

**Comment by ewlarson** [comment]
This doc fails to render citation because Chronic (a ruby library to parse dates) cannot parse: "2004-01-00". The "00" day value is invalid and the troublemaker here. Updating the doc to "2004-01-01" would work, but I'll also just make the citation logic a bit smarter here.
