### ISSUE TITLE
Create Catalog#admin view for document

### ISSUE THREAD

**Issue by ewlarson** [BTAA-Geospatial-Data-Project/geoportal#260]
Develop a "/admin" view for documents. This new view will allow B1G staff to see administrative results for any solr document:

* SolrDocument
* ItemViewer protocol
* Thumbnail harvest state
* URI harvest states

**Comment by ewlarson** [comment]
![admin_example](https://user-images.githubusercontent.com/69827/67241925-0911cf80-f41a-11e9-86b5-6d41615fa7ca.png)

**Comment by mberkowski** [comment]
Will this be needing any authentication in the end?

**Comment by ewlarson** [comment]
@mberkowski Not unless we add some controls to re-run URI checking or Thumbnail harvesting here. All the data in B1G is freely available.

**Comment by ewlarson** [comment]
@karenmajewicz "Admin view" is up on geodev. Here's an example:
https://geodev.btaa.org/catalog/06e7f566-852a-4914-929d-1bef38132eba/admin

**Comment by karenmajewicz** [comment]
This is great - very useful.
