### ISSUE TITLE
Indicate to user when web services won't/cant load

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/geoportal#261]
A common complaint is that ArcGIS web services are not displaying. This occurs for many reasons. Here are a few:

* the service was deleted from the source
* the service is not being delivered over https
* CORS policy incompatibilities (ex. https://geodev.btaa.org/catalog/b06d96e4-c917-4afc-a3df-adbbc9a2273c). 
* the service is just large and takes forever to load.
* the service has a visibility scale range outside of the map extent.

What kind of messages can we display to indicate problems with the service?

**Comment by ewlarson** [comment]
[CORS errors are hard to capture by design](https://stackoverflow.com/a/6734427/431161).

The best we can do for those will be to make a pre-GET request for the map data-url, to see if a "network error" will happen. If no error, we have nothing to worry about. If we have an error, we can do something to the UI to show a problem has occurred.

Here's an example I have working locally:

<img width="1280" alt="Screen Shot 2019-10-22 at 4 33 14 PM" src="https://user-images.githubusercontent.com/69827/67336031-480f5600-f4ea-11e9-914b-fe7371d06459.png">

**Comment by karenmajewicz** [comment]
That button and text looks good. Would it be possible for it to overlay the map?

**Comment by karenmajewicz** [comment]
Example of web service that was deleted from source: https://geodev.btaa.org/catalog/4d2053c593cc4f7685f2823f9e2061b8_1

**Comment by ewlarson** [comment]
@karenmajewicz Can you please post some additional examples?

* the service is not being delivered over https
* the service is just large and takes forever to load.
* the service has a visibility scale range outside of the map extent.

Having some examples for these three would greatly help!

**Comment by karenmajewicz** [comment]
the service is just large and takes forever to load:
https://geodev.btaa.org/catalog/ab0f0408fcb5479e97df5a13d9a3c648_0

Most of the records called "Address points" take a long time and can seemingly freeze the application.

**Comment by karenmajewicz** [comment]
the service has a visibility scale range outside of the map extent:
https://geodev.btaa.org/catalog/458cf4b7d44543d2a3bee3bd92914af9_3

**Comment by ewlarson** [comment]
@karenmajewicz Okay! Silly question... but how do you know which of these maps/viewers work and which do not work?

I ask because, as we capture errors here, we could also add a little ItemViewer state tracker here to record success and failure. Once that data populates the database, we could report on it.

Sound interesting?

**Comment by karenmajewicz** [comment]
For the one with an https one, I looked at the URI analysis report, which returned the error `"#<OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=SSLv2/v3 read server hello A: unknown protocol>`

Is that the kind of thing you are looking for? The others were more of a manual sleuthing, but we might be able to figure out a programmatic way of determining them?

**Comment by karenmajewicz** [comment]
Are you able to query attributes on the JSONs? (https://xmaps.indy.gov/arcgis/rest/services/OpenData/OpenData_Boundaries/MapServer/3?f=pjson)? If so, we could look for things that might trip up the viewer, such as number of features, the projection, and the min/max view.

**Comment by ewlarson** [comment]
The really slow Address Points feature_layer maps might perform substantially better using [esri-leaflet-cluster](https://github.com/Esri/esri-leaflet-cluster)

I'll see if I can make that happen.

**Comment by karenmajewicz** [comment]
If clustering is an option, that could really help. Just trying to browse the geoportal by service (https://geodev.btaa.org/?f%5Bdc_type_sm%5D%5B%5D=Service&q=&search_field=all_fields) is really frustrating, because users run into laggy web services very quickly.

**Comment by ewlarson** [comment]
How does this feel?

<img width="1280" alt="Screen Shot 2019-10-24 at 10 52 56 AM" src="https://user-images.githubusercontent.com/69827/67502997-7f961380-f64c-11e9-845d-0511330f7983.png">

**Comment by karenmajewicz** [comment]
I like the darkened overlay and the sentence message. I am not sure about the phrase "Our Apologies".... I'll look at some similar site error messages to see if there is another phrase.

**Comment by ewlarson** [comment]
FYI - I've added Google Analytics event tracking for "Item Viewer Error", too.
