### ISSUE TITLE
add clustering to web services with many features

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/geoportal#262]

**Comment by ewlarson** [comment]
This feature branch is up on geodev now. Take a look at the performance difference between:

GeoProd (~4,000 points):
https://geo.btaa.org/catalog/ab0f0408fcb5479e97df5a13d9a3c648_0

GeoDev (Clustered):
https://geodev.btaa.org/catalog/ab0f0408fcb5479e97df5a13d9a3c648_0

**Comment by karenmajewicz** [comment]
This is fantastic! What an improvement for users.

**Comment by ewlarson** [comment]
Ah... found a bug. All the homepage popups show the same text and URL. Working on a fix...

**Comment by ewlarson** [comment]
Bug fixed. Code updated on geodev. Closing as feature is in develop now.
