### ISSUE TITLE
Adjust zoom levels for feature layer clusters

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/geoportal#267]
Users should be able to see each feature at maximum zoom. Currently, many services are still clustered when the user zooms in as much as they can. 

Maybe the leaflet zoom level should be adjusted as well?

**Comment by karenmajewicz** [comment]
Here is an example: when zoomed in as far as possible, the clusters are still present. https://geodev.btaa.org/catalog/77c3283978464432b9a391b8b9cf7885_0

**Comment by ewlarson** [comment]
Example of the issue:
<img width="1280" alt="Screen Shot 2019-11-20 at 9 06 58 AM" src="https://user-images.githubusercontent.com/69827/69250391-2fd83880-0b75-11ea-95ab-cef2168ebefe.png">

When these points are spidered, clicking returns the data at the center of the web, not the point data.

Maybe this list plugin would be better:
https://adammertel.github.io/Leaflet.MarkerCluster.List/demo/demo1.html

**Comment by ewlarson** [comment]
One note here: The ESRI basemap supports a max zoom of 18. If you allow the map to zoom further (19+), you get no map background tiles.

Maybe another basemap would be better?

**Comment by karenmajewicz** [comment]
That's an interesting idea. Perhaps we could include the option for the user to select a different basemap. like this -  https://esri.github.io/esri-leaflet/examples/layers-control.html
