### ISSUE TITLE
Thumbnails for collections working on dev; not prod

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/geoportal#268]
Trying to figure out why the thumbnail harvest for collection level records was only successful on the development server. Compare:

Thumbnail succeeded: https://geodev.btaa.org/catalog/02b-17091/admin
Thumbnail placeheld: https://geo.btaa.org/catalog/02b-17091/admin

This may be related to issue #254, where items without downloads didn't have a thumbnail.

**Comment by mberkowski** [comment]
Thumbnailing logs are entirely empty on prod for the past 2 weeks, though filling on dev. I'll see if I can determine why.

**Comment by mberkowski** [comment]
`02b-17091` succeeded in loading a thumbnail on Oct 27, 2 days after the latest deploy. @karenmajewicz you pointed me toward a production issue - the Solr service problems we had a few weeks ago and the temporary fix to cut over to an alternate service port resulted in Sidekiq holding onto an incorrect Solr URL for a bunch of jobs, and the sidecar images harvest wasn't running. I've got it churning through now and will keep an eye out for this record to complete.

It seems likely it will - here is an example of a comparable one which did get a thumbnail today: https://geo.btaa.org/catalog/06a-02/admin

**Comment by mberkowski** [comment]
Update: `02b-17091` did get a thumbnail this morning, so this was a production integration issue unrelated to #254.
