### ISSUE TITLE
Address incompatibilities with MS browsers: Internet Explorer & Edge

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/geoportal#269]
Here are a few issues that were reported to me and some that I checked using an online IE renderer (which may not be accurate):

- The homepage of the geoportal does not display in Internet Explorer 11.
- The map on the homepage does not display in Edge
- The Mirador viewer does not display in IE 11 (possibly the Leaflet IIIF viewer as well)

We should define our level of support for these browsers somewhere.

**Comment by ewlarson** [comment]
IE 11 and Edge are both throwing JS issues. IE 11 has some homepage CSS styling issues to resolve, too. Bootstrap supports IE 10, 11 and Edge, so we should be able to fix these issues.

I'm not sure where Mirador stands on browser support. Will troubleshoot next week.

**Comment by ewlarson** [comment]
There are three things here that need attention:

- [X] DOM/CSS layout for IE 11
- [ ] Blacklight JS error in IE (11 and Edge)
- [ ] Mirador JS error
- [ ] GeoBlacklight / Blacklight SVG icon warnings  

### DOM/CSS layout for IE
Revisited and improved the bootstrap-based layout for the homepage. DOM renders correctly in IE 11 and Edge now. 

### SVG icon warnings
Need to strip XML namespace and DOCTYPEs from SVG icons -- already done in GBL, but not done in B1G.

### Blacklight JS Error (11)
Error occurs in blacklight.js here:
```
document.querySelectorAll('button.collapse-toggle').forEach(button...
```
See IE forEach support: https://stackoverflow.com/a/54344650/431161

### Mirador JS Error (Edge)
Error occurs in mirador.min.js
```
removeTrailingSlash:!0,removeDirectoryIndex:!1,sortQueryParameters:!0,...t},
```
SCRIPT1028: Expected identifier, string or number
