### ISSUE TITLE
Version 1.4 - Map not responding to facets.

### ISSUE THREAD

**Issue by KarenMajewicz** [BTAA-Geospatial-Data-Project/geoportal#27]
When you select facets on the search results page, the map is supposed to zoom/recenter based upon the results. Compare [prod](https://geo.btaa.org/?f%5Bdct_spatial_sm%5D%5B%5D=Minnesota%2C+United+States) to [dev](https://geodev.btaa.org/?f%5Bdct_spatial_sm%5D%5B%5D=Minnesota%2C+United+States) with one facet selected.

  In the 1.4 dev site, the map remains zoomed out no matter what you select.  Could this be related to this commit? - https://github.com/geoblacklight/geoblacklight/pull/515

**Comment by ewlarson** [comment]
Actually, it's this PR that is causing issues for us: https://github.com/geoblacklight/geoblacklight/pull/520

I'll poke about some more for a solution.

**Comment by ewlarson** [comment]
Have a fix for us locally, and have opened this PR with GeoBL:  https://github.com/geoblacklight/geoblacklight/pull/537
