### ISSUE TITLE
Select datasets for licensed data pilot

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/geoportal#271]
- [x] Gather basic metadata about the service. 

- [x] Gather which institutions subscribe

- [x] Document specific access rights per institutions (locations, years, etc.)

- [x] Gather access links for each institution

**Comment by karenmajewicz** [comment]
Here are records for the licensed data application called Social Explorer using our current functionality: 

- On Dev: https://geodev.btaa.org/catalog/99-0001

- individual JSONs: [99-0001.zip](https://github.com/BTAA-Geospatial-Data-Project/geoportal/files/3865708/99-0001.zip)

**Comment by karenmajewicz** [comment]
Here are sample records for LandScan:

- On Dev: https://geodev.btaa.org/catalog/99-0002

- JSONs: [99-0002.zip](https://github.com/BTAA-Geospatial-Data-Project/geoportal/files/3865850/99-0002.zip)

**Comment by ewlarson** [comment]
Here's a first take at getting licensed resource access links into the "Links" sidebar menu. I'm adding the padlock icon back to the title for restricted items only. Also, adding the padlock to the Links subheading to tie back towards the links visually.

![geoportal_licensed_resource_example](https://user-images.githubusercontent.com/69827/69360934-11e00600-0c51-11ea-9e53-646e8ba28146.png)

Thoughts?

**Comment by karenmajewicz** [comment]
Does the user need more info? Maybe a rollover text help?

**Comment by karenmajewicz** [comment]
[There are now 3 records in the geoportal that we can use for evaluation. ](https://geodev.btaa.org/?f%5Bdc_type_sm%5D%5B%5D=Interactive+Resource&search_field=all_fields)

- [Social Explorer with links to each institution's library catalog permanent link](https://geodev.btaa.org/catalog/99-0001)
- [Social Explorer with links to each institution's proxy login](https://geodev.btaa.org/catalog/99-0001-test)
- [LandScan with links to each institutions library catalog permanent link](https://geodev.btaa.org/catalog/99-0002)

Each record has:

- [ ] a date range field 
- [ ] rollover help text
- [ ] padlock symbol for restricted access
- [ ] a field with the text names of the schools with access (dct_mediator_sm)
- [ ] a field with key:value pairs for school:link (b1g_access_s)
