### ISSUE TITLE
Read More links not responding on production site

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/geoportal#276]
The Read More function appears to work on the dev site, but not prod.  examples:

does not respond: https://geo.btaa.org/catalog/cc25f6cc-ae03-4240-997e-d2c4d7986943
works: https://geodev.btaa.org/catalog/cc25f6cc-ae03-4240-997e-d2c4d7986943

https://geo.btaa.org/catalog/472e21ca6a974871ae31f09b559c9f07_0
https://geodev.btaa.org/catalog/472e21ca6a974871ae31f09b559c9f07_0

Same behavior on admin view:
https://geo.btaa.org/catalog/472e21ca6a974871ae31f09b559c9f07_0/admin
https://geodev.btaa.org/catalog/472e21ca6a974871ae31f09b559c9f07_0/admin

**Comment by mberkowski** [comment]
The Read More links are all working correctly for me on prod, in Chrome and Firefox. @karenmajewicz can you do a hard refresh in case you lost some javascript? Or try them in a private/incognito browsing window?

**Comment by karenmajewicz** [comment]
Thanks for checking @mberkowski. You are right - I just tried Chrome & Firefox and they did indeed both respond correctly.

So the problem only happens in my alternative browser, Brave (Chrome based), which must be blocking some javascript. Oddly, even after clearing my cache and trying a private window, this browser still produces the odd effect where readmore works in dev, but not prod.

Seems like this is not a problem, but I wondered if it might have revealed some slight difference in our javascript between the dev and prod.

**Comment by ewlarson** [comment]
https://geo.btaa.org/catalog/cc25f6cc-ae03-4240-997e-d2c4d7986943
Read more links in Brave are working for me here: Version 1.1.21 Chromium: 79.0.3945.79 (Official Build) (64-bit)

Closing this issue. Please re-open if the problem persists.

**Comment by karenmajewicz** [comment]
Yes, it's working for me too on the new version of Brave. (I wondered if it was related to #286 CrazyEgg, which we can look into later.)
