### ISSUE TITLE
Mirador - Implement download plugin

### ISSUE THREAD

**Issue by ewlarson** [BTAA-Geospatial-Data-Project/geoportal#281]
Cut branch to test mirador download plugin. Found JS errors in Chrome, FF, Safari. Documented and shared with Mirador community via ticket:
https://github.com/ProjectMirador/mirador-dl-plugin/issues/40

TODO:
Try debugging with PSU CDM-generated manifest.

**Comment by ewlarson** [comment]
Updated to mirador 3 beta 0. Still seeing issues as documented on the mirador-dl-plugin repo here:
https://github.com/ProjectMirador/mirador-dl-plugin/issues/43

**Comment by karenmajewicz** [comment]
May revisit after official release. In the meantime, we are using Universal Viewer
