### ISSUE TITLE
enable downloads for Mirador IIIF items

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/geoportal#283]

**Comment by karenmajewicz** [comment]
Downloads are available through plugin, but the function is hidden

**Comment by karenmajewicz** [comment]
https://geo.btaa.org/catalog/p16022coll245:973

**Comment by karenmajewicz** [comment]
add issue to Mirador project

**Comment by karenmajewicz** [comment]
https://github.com/ProjectMirador/mirador/issues/1397

Closing issue as the function exists; Mirador design may need updating to improve usability.

**Comment by ewlarson** [comment]
Add custom download icon, like SUL:
https://github.com/sul-dlss/sul-embed/pull/1101

**Comment by ewlarson** [comment]
Errors after upgrading Mirador and the Mirador download plugin:

<img width="1280" alt="Screen Shot 2020-03-23 at 5 14 04 PM" src="https://user-images.githubusercontent.com/69827/77429408-9f6e6680-6da7-11ea-9a36-a213105fe6b0.png">

Upgraded Mirador packages also display less download resolutions:

<img width="1280" alt="Screen Shot 2020-03-23 at 5 13 49 PM" src="https://user-images.githubusercontent.com/69827/77429565-dc3a5d80-6da7-11ea-9289-ba5164f32e66.png">

**Comment by ewlarson** [comment]
Upgraded to latest releases: mirador 3.0.0-beta.6 and mirador-dl-plugin 0.11.0

Error still occurs when clicking the "vertical ellipse" icon... 

<img width="1280" alt="Screen Shot 2020-03-24 at 8 48 56 AM" src="https://user-images.githubusercontent.com/69827/77432714-713f5580-6dac-11ea-9259-c67afe31afe9.png">

**Comment by ewlarson** [comment]
@karenmajewicz -- I'm going to pause development on this issue for this code sprint (March '20). We can try again when Mirador development stabilizes.

**Comment by ewlarson** [comment]
Related #304
