### ISSUE TITLE
Address Crazyegg cookie warning / Not seeing anything about it on CE help documentation...

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/geoportal#286]

**Comment by ewlarson** [comment]
Yeah, I looked into this once and couldn't find anything in their docs. Chrome is setting this warning for a future cookie policy change. So, this is something that the third-party cookie setter, here it's Crazyegg, will need to handle on their end.

It's just a warning, so it doesn't impact the application or our code at all.
