### ISSUE TITLE
Missing metadata: do not require layer_geom_type_s 

### ISSUE THREAD

**Issue by ewlarson** [BTAA-Geospatial-Data-Project/geoportal#294]
Per https://github.com/geoblacklight/geoblacklight/issues/855

We want to no longer require layer_geom_type_s, but we're using it to display SVG icons on result list view.

<img width="1280" alt="Screen Shot 2020-01-24 at 10 10 42 AM" src="https://user-images.githubusercontent.com/69827/73084277-49a63c80-3e92-11ea-9fb4-a19a7456237c.png">

**Comment by karenmajewicz** [comment]
This field has been deprecated for the new metadata schema and GeoBlacklight versions.
