### ISSUE TITLE
Troubleshoot suppressed feature

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/geoportal#305]
Our Solr instance shows that we have 28674 public records in our production site. However, only 27,971 display in our search results.

This discrepancy became clear after we published our last set of ArcGIS records. They are functioning like they are suppressed, but the value for that field is marked correctly as false. What else might be causing them not not return in searches?

Example:

I can find this record if I go directly to its landing page: https://geo.btaa.org/catalog/93acb22870174b48adfa73b0c6f95f0d_9

But, it doesn't show up in searches. 

- Searching by Identifer: https://geo.btaa.org/?utf8=%E2%9C%93&search_field=all_fields&q=93acb22870174b48adfa73b0c6f95f0d_9

- Searching by Date Accessioned: https://geo.btaa.org/?f%5Bb1g_dateAccessioned_s%5D%5B%5D=2020-03-06

compare this last search with our development site, which works as expected:
https://geodev.btaa.org/?f%5Bb1g_dateAccessioned_s%5D%5B%5D=2020-03-06

**Comment by ewlarson** [comment]
Three things at play here:

1. Solr documents
2. Solr configuration
3. Application code/logic/configuration

The solr docs are the exact same on geodev and geoprod. The application code should be the exact same on both geodev and geoprod, too. Maybe our solr config is somehow different between the environments?

@mberkowski Could you help us out here? Can you try and diff the geoprod and geodev solr configs?

**Comment by mberkowski** [comment]
Both servers are reporting solr config via git as 
```
$ git status
# HEAD detached at 2.3.0
nothing to commit, working directory clean
```
And both are pointing at the production core `http://localhost:8983/solr/production`

**Comment by mberkowski** [comment]
I restarted production Solr and now it seems to appear in searches. I wonder if Solr was hadn't been restarted after the last config update? Seems like we would have noticed because other features could have been missing. But the prod server has been online a couple of months longer than since the dev server was last rebooted, so if neither Solr had been restarted on a deploy the dev would have picked it up on a reboot.

**Comment by ewlarson** [comment]
Yeah, that definitely fixed the issue... but I'm not sure what was wrong to begin with. It's almost like the docs on geoprod were indexed but not fully committed?

**Comment by ewlarson** [comment]
Closing as issue has past.
