### ISSUE TITLE
Return the bounding box inset for maps from Indiana

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/geoportal#306]
Bounding box insets must have gotten removed for this collection when the static image was readjusted to display for these items. Here is an example: https://geodev.btaa.org/catalog/VAC9619-001735

They still appear for other maps in the geoportal.

**Comment by ewlarson** [comment]
![О-34-126-B 127-А Лиэпайя  Liepāja  Latvia  - Big Ten Academic Alliance Geoportal](https://user-images.githubusercontent.com/69827/80388466-8b6ac880-886f-11ea-9193-6cd55f7a805f.png)
