### ISSUE TITLE
Add dct_accessRights_sm to Item View page

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/geoportal#307]
`dct_accessRights_sm` is a new field for licensed data and can be displayed with the label "Access Rights"

This is only needed on the Dev site for now.

**Comment by ewlarson** [comment]
Example below. This will only display if dct_accessRights_sm values are present on the document. 

![Social Explorer - Big Ten Academic Alliance Geoportal](https://user-images.githubusercontent.com/69827/80398035-aa238c00-887c-11ea-9967-5eead4f20eea.png)

**Comment by karenmajewicz** [comment]
[Tested on the dev site ](https://geodev.btaa.org/catalog?f%5Bdct_isPartOf_sm%5D%5B%5D=99-0002)- looks good.
