### ISSUE TITLE
May Blog Post

### ISSUE THREAD

**Issue by KarenMajewicz** [BTAA-Geospatial-Data-Project/geoportal#31]
# New Records from the cities of Chicago, IL and Bloomington IN, plus Minor Interface Changes
### Chicago, Illinois
109 geospatial records were recently added to the geoportal from the [City of Chicago's Open Data Portal](https://data.cityofchicago.org/), notably dozens of records about[ public schools in the city.](https://geo.btaa.org/?f%5Bdct_isPartOf_sm%5D%5B%5D=City+of+Chicago+Data+Portal&per_page=100&q=schools&search_field=all_fields)
![chicagopublicschools](https://cloud.githubusercontent.com/assets/2367677/25535967/8a268ce6-2bfe-11e7-8084-aa313497831f.png)

### Bloomington, Indiana
17 GIS records were added from the [City of Bloomington Data Portal](https://data.bloomington.in.gov/organization/city-of-bloomington). These records have web services that are hosted with GeoServer, and feature nicely styled layers.
![bloomington](https://cloud.githubusercontent.com/assets/2367677/25642186/d90b404c-2f5d-11e7-90a1-654efcc27e42.png)

### Browse all records
Users can now more easily browse all records by clicking on the search button on the homepage without entering text in the search box.

![clickhere](https://cloud.githubusercontent.com/assets/2367677/25536214/96050410-2bff-11e7-9ffe-eae735ea2965.png)

### New Facet Order
The left hand facets on the search results page have also been reordered with Place and Data Type at the top.  This change is the result of usability tests that indicated these would be the most helpful categories for filtering records.
![facetorder2](https://cloud.githubusercontent.com/assets/2367677/25536581/00108a2c-2c01-11e7-959f-32aa299c85c3.png)

## Finding a broken link?

We are continually working on maintaining the currentness of records, including fixing broken links. If you find a broken link or discover a dataset is no longer available, [please contact us!](https://docs.google.com/a/umn.edu/forms/d/e/1FAIpQLSf6OHrj6YIcn8yNe6sWgQJ_iJfElDZgozUCSdATzePwLqul5Q/viewform)

**Comment by ewlarson** [comment]
On development server here:
https://geodev.btaa.org/blog/2017/05/02/new-records-and-interface-changes.html

Any changes required, or shall I push to production?

**Comment by KarenMajewicz** [comment]
Looks fine.  Thanks!

**Comment by KarenMajewicz** [comment]
I realized I didn't add the Bloomington section.  When you publish to the prod site, could you add this new version instead?  Thanks.
