### ISSUE TITLE
Q. How do I replace stored centroids for published records? We fixed these https://geo.btaa.org/catalog/01d-03, but the homepage still displays the incorrect, originally uploaded centroids.

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/geoportal#310]

**Comment by ewlarson** [comment]
Thanks! @mberkowski -- Yeah, I'm surprised we didn't notice this oversight earlier.

**Comment by ewlarson** [comment]
Wiki entry on homepage centroids here:
https://github.com/BTAA-Geospatial-Data-Project/geoportal/wiki/Homepage-Map-Clusters-and-Centroids

Closing this issue now. @karenmajewicz Please reopen if you have any questions or need any additional assistance.
