### ISSUE TITLE
Add year "buckets" for a time period facet

### ISSUE THREAD

**Issue by KarenMajewicz** [BTAA-Geospatial-Data-Project/geoportal#32]
Here is a possible breakdown:

1500s
1600s
1700s
1800-1849
1850-1899
1900-1949
1950-1999
2000-2004
2005-2009
2010-2014
2015-present
No date

**Comment by ewlarson** [comment]
Have a branch where I'm working on this issue.  Will show you tomorrow.
![screen shot 2017-06-06 at 3 09 15 pm](https://user-images.githubusercontent.com/69827/26849537-3586927c-4aca-11e7-9ccb-e75cc14e8cf4.png)

**Comment by KarenMajewicz** [comment]
Looks great!

**Comment by KarenMajewicz** [comment]
I checked with the Interface Steering Group and they all suggested that we try to emphasize the connection between the Time Period and the Year facets. So, can we try moving the Time Period facet down one place?

**Comment by ewlarson** [comment]
Certainly.  I've got that placement up on the dev site now:
https://geodev.btaa.org/?utf8=%E2%9C%93&search_field=all_fields&q=

Let me know if you want this moved to production.

**Comment by KarenMajewicz** [comment]
That looks good - please go ahead and publish.

**Comment by ewlarson** [comment]
This is live now.  Cheers!
