### ISSUE TITLE
Assess if Child record values are adequate

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/geoportal#325]
We published a new collection of records (Access Across America series) with the child element set to true. These records show up very high in the search results.

Using the Is Part Of: https://geodev.btaa.org/catalog?f%5Bdct_isPartOf_sm%5D%5B%5D=05d-03

Using the Subject value of Transportation: https://geodev.btaa.org/?f%5Bb1g_genre_sm%5D%5B%5D=Geospatial+data&f%5Bdc_subject_sm%5D%5B%5D=Transportation&page=1&per_page=100

**Comment by ewlarson** [comment]
Okay! Looking at debugQuery results, everything in a simple facet search is returning a score of 1.0.

I think this is just a feature implementation issue. Our boost function is only checking for the presence of the b1g_child_record_b field. It's not checking the value of that boolean field. I think originally I expected the field to only exist on child docs (as "true), not also on collection/parent docs (as "false") -- kinda silly of me.

We can just modify the boost to identify the value and act accordingly. I'll grab some fixtures and change the boost.
