### ISSUE TITLE
June Blog Post

### ISSUE THREAD

**Issue by KarenMajewicz** [BTAA-Geospatial-Data-Project/geoportal#33]
# New records from Washington, D.C. and Scott County, MN; Geospatial Metadata Workshop materials

### Washington, D.C.
During May 2017, [805 new GIS records from Washington, D.C.’s Open Data Portal](https://geo.btaa.org/?f%5Bdct_isPartOf_sm%5D%5B%5D=District+of+Columbia+Open+Data&search_field=all_fields) were added to our geoportal.  Washington, D.C. has published an extensive collection of geospatial datasets with several interesting categories of datasets, including ongoing public services ([abandoned vehicles](https://geo.btaa.org/catalog/485134cd-0a52-46b2-97c3-bf86cb60423d), [dead animal pickup](https://geo.btaa.org/catalog/b7d03a63-e7a2-4185-9141-9f68ef070ee3)), cultural analyses ([artist density](https://geo.btaa.org/catalog/e829c8d2-8362-446c-b04f-32e83eaee98e), [memorials](https://geo.btaa.org/catalog/15673154-69f9-4410-9d64-d741c27a771d)), and over [200 records related to Vision Zero](https://geo.btaa.org/?f%5Bdc_subject_sm%5D%5B%5D=Vision+Zero&search_field=all_fields), the city’s plan to eliminate traffic fatalities.
<br>
![museumsdc](https://cloud.githubusercontent.com/assets/2367677/26604756/f1aae3f6-4550-11e7-8ce0-0d6ecc86c1ce.png)
<br>
[Locations of museums in Washington, DC](https://geo.btaa.org/catalog/bf7b4b72-27e8-4d17-8fec-76a6078a32d8)
<br>
### Scott County, Minnesota
Open data for Minnesota counties continues to expand, and this month we added 28 records from [Scott County](https://geo.btaa.org/?f%5Bdct_isPartOf_sm%5D%5B%5D=Scott+County+Open+Data&search_field=all_fields).
![foodresourcesscottcountymn](https://cloud.githubusercontent.com/assets/2367677/26605047/14528d36-4552-11e7-8610-2b0d041f20e5.png)
[Food Resources in Scott County, Minnesota](https://geo.btaa.org/catalog/1e7f9235-b8e2-4539-bc26-574c96d2b5de)
<br>
<br>
## GEOSPATIAL METADATA WORKSHOP
The month of May also brought the beginning of our metadata outreach efforts in the form of a 3 hour session presented at the Minnesota GIS/LIS Spring Workshops.  Karen Majewicz and Melinda Kernik led the workshop, which covered the importance of metadata, standards and tools, techniques for batch generating technical and administrative elements, and a discussion of what makes good descriptive metadata. [View and download the workshop materials here.](https://drive.google.com/open?id=0Byl0jXcFUSJ-eDZTYzJsU1Uya1k)
![creatinggeospatialmetadata](https://cloud.githubusercontent.com/assets/2367677/26605222/cf0ffbc2-4552-11e7-9dff-f7c3745eeaca.png)

**Comment by ewlarson** [comment]
Just pushed this onto the development server.  Can you take a look and let me know if I should push to production?  Thanks!
https://geodev.btaa.org/blog/2017/06/06/new-records-and-geospatial-metadata-workshop.html

**Comment by KarenMajewicz** [comment]
The spacing is a little tight and the caption for the first image is wrapped with the image.  I added some <br>.  Is that a good way to solve these problems?

**Comment by KarenMajewicz** [comment]
Some line breaks "br"

**Comment by ewlarson** [comment]
Line breaks are evil (and mostly ignored by browsers).  Let's avoid them.

I've added a CSS rule to the blog post images that will make them take the full-width of the blog post column.

Overall, blog's type is mostly confined to just headers and paragraph text, borrowing the line-height and margin/padding rules that govern the entire web application.  We can make changes to add a bit more space around headers pretty easily, but we need to be careful not to make the application wonky just to style the blog a bit nicer.  Make sense?

Give it another look.  We can push this live and make some tweaks when we meet tomorrow, too.

**Comment by KarenMajewicz** [comment]
OK, thanks for fixing the image width property.  Yes, I get what you are saying about the margin/padding rules idea.  I see that there are classes in the scss for [posts.](https://github.com/BTAA-Geospatial-Data-Project/geoportal/blob/2e0725e0b5bf7ff7e2d472727762da9b9fc61bb6/blog/_sass/minima/_layout.scss)  Maybe we could create an h2 post-subtitle class with top-padding?

**Comment by ewlarson** [comment]
Certainly.  Added some additional padding to post h2 elements here:
https://geodev.btaa.org/blog/2017/06/06/new-records-and-geospatial-metadata-workshop.html

**Comment by KarenMajewicz** [comment]
Looks good, thanks!

**Comment by ewlarson** [comment]
Pushed live!
