### ISSUE TITLE
ArcGIS REST Feature Services - UI adjustments

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/geoportal#337]
Some Feature Services are not queryable. Here is an example: https://geo.btaa.org/catalog/714589fbf99d4045bc57bf298be2578e_0 (this one produces an Uncaught TypeError)

Two questions brought up by TF in recent meeting:
- Why is the cursor different when clicking on feature services than for the MapServer type?
- Can the text at bottom that says _Click on map to inspect values_ be changed if the service is not clickable?

See #278

**Comment by karenmajewicz** [comment]
This example: https://geo.btaa.org/catalog/c759946b9de848fbba0f508d431e04bc_0

**Comment by karenmajewicz** [comment]
More possible insight: FeatureServer queries on point layers might be working fine: https://geo.btaa.org/catalog/9e5e784e718b46838d7c99f3a66caab1_1

Here is the same basic data, from the same organization, but presented as polygons: https://geo.btaa.org/catalog/019f5e3f77da4c89bf6d00b376389a0c_1 (need to scroll in a ways to view the layer). Clicking on the data preview doesn't produce any attributes displayed in the table.

**Comment by karenmajewicz** [comment]
Here is a Map Server record: https://geo.btaa.org/catalog/b3acc7df1a484c10b46072e2dc009894_1
When clicking on a polygon, the cursor is a +

Here is a Feature Server record: https://geo.btaa.org/catalog/714589fbf99d4045bc57bf298be2578e_0
When clicking on a polygon, the cursor is a hand.

**Comment by ewlarson** [comment]
#### Why is the cursor different when clicking on feature services than for the MapServer type?

GeoBlacklight sets the default cursor style to crosshair via this [selector](https://github.com/geoblacklight/geoblacklight/blob/main/app/assets/stylesheets/geoblacklight/modules/item.scss#L8-L22). GeoBlacklight also contains Leaflet's stylesheet which sets [.leaflet-interactive](https://github.com/geoblacklight/geoblacklight/blob/main/vendor/assets/stylesheets/leaflet.css#L204-L206) to pointer.

It's a GBL bug. We can change that style rule locally if you (anyone) have strong opinions.

Should we force crosshair for .leaflet-interactive svg paths?

#### Can the text at bottom that says Click on map to inspect values be changed if the service is not clickable?

It's very difficult to know if the data will ultimately be queryable or not. Some records are so large and load so slowly (see [Tenure](https://geo.btaa.org/catalog/019f5e3f77da4c89bf6d00b376389a0c_1)), the visualization might not appear for over half a minute or more. Also, it's very difficult to know if an error will result upon clicking.

It's best to report documents with bad behaviors for debugging and troubleshooting.

**Comment by karenmajewicz** [comment]
We want the cursor to be the same for both types of services - which would be easier to override? The crosshatch is a little easier to be more precise with.

I think it is OK to disregard the second question about customized text for broken services.
