### ISSUE TITLE
Enable Google Search Console (?)

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/geoportal#339]
We are planning to run a Google Ads Campaign later this year, so I am exploring what keywords might perform the best to drive users to our site. I would like to enable Google Search Console for the site. (https://search.google.com/search-console/about). This needs to be enabled in the DNS configuration.

Are there reasons why we might not want to do this?

**Comment by ewlarson** [comment]
Can't think of any reason not to pursue Google Search Console. Looks like the [DNS verification steps](https://support.google.com/webmasters/answer/34592) are harder than when I last set it up -- when you just dropped something into the HTML head.

You will need to work with Michael/Paul and likely UIUC to get the verification txt snippet into the DNS record. Tagging Michael in here for him to follow up.

**Comment by mberkowski** [comment]
Looking quickly at the docs, are we not able to use the URL prefix verification, which can be done various ways without modifying DNS? I was thinking if we could just use `https://geo.btaa.org/` as the prefix, then it looks like meta tags and HTML file checks are still supported. I only glanced at this - am I missing something that requires us to verify the full domain?

**Comment by ewlarson** [comment]
OH! I think you are right. Sorry for the confusion. @karenmajewicz let's try the prefix path here.

**Comment by karenmajewicz** [comment]
Thanks, Michael. I see that option now for a <meta> tag.

**Comment by karenmajewicz** [comment]
Verfied.
