### ISSUE TITLE
Tests - B1G Index Map file 404s

### ISSUE THREAD

**Issue by ewlarson** [BTAA-Geospatial-Data-Project/geoportal#349]
The B1G Index Map that we use in our Geoportal application test suite, has gone missing:
https://raw.githubusercontent.com/BTAA-Geospatial-Data-Project/indexmaps/master/dakota.geojson

Is there a new URL for this map?

**Comment by karenmajewicz** [comment]
Yes, I just reorganized that repo. The new link is https://raw.githubusercontent.com/BTAA-Geospatial-Data-Project/indexmaps/main/data/05d-01/dakota.geojson

**Comment by karenmajewicz** [comment]
I updated the link in our Aardvark CSV file: in the metadata update repo (https://github.com/BTAA-Geospatial-Data-Project/GBL-Schema-Update)
