### ISSUE TITLE
Right padding on Visit Source button missing in dev geoportal (GBL version 3.3)

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/geoportal#353]
![Screen Shot 2021-04-26 at 11 54 58 AM](https://user-images.githubusercontent.com/2367677/116121479-434ed380-a686-11eb-8e2d-6b22c55d76ba.png)

**Comment by ewlarson** [comment]
<img width="286" alt="Screen Shot 2021-05-03 at 3 27 35 PM" src="https://user-images.githubusercontent.com/69827/116929510-24bb8000-ac24-11eb-9dc0-8e1882b6a8a7.png">
