### ISSUE TITLE
Consider disabling the spatial display update from the GeoBlacklight version 3.3

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/geoportal#359]
From what I think I am seeing, the updated GeoBlacklight is causing a number of problems for coordinates.  The application will error if a record:

- is missing coordinates
- has coordinates that form a point or line.

We have many records that fall into one of these scenarios. Recent versions of GeoBlacklight did not require bounding boxes or displayed points/lines OK. I am not sure if I will be able to find all of these, so it seems likely that we will end up with many error pages before GBL 4.0 is ready.

Would it be possible to revert to previous code for that part only?

**Comment by karenmajewicz** [comment]
This might be incorrect. I was able to manually add a record without any coordinates. Will continue troubleshooting.

**Comment by ewlarson** [comment]
Please add any related URLs for failing records here for troubleshooting.

**Comment by karenmajewicz** [comment]
LinearRing is failing: https://geodev.btaa.org/?f%5Bgbl_resourceClass_sm%5D%5B%5D=Maps&f%5Btime_period%5D%5B%5D=2015-present. Some kind of map from 2015 I think is doing this, but I can't get it to open.

**Comment by karenmajewicz** [comment]
Found it:
https://geo.btaa.org/catalog/ANT-REF-MP2015-001
https://geodev.btaa.org/catalog/ANT-REF-MP2015-001

I wonder if it is related to being polar.
