### ISSUE TITLE
Do we want type icons for items, especially those without thumbnails?

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/geoportal#362]
Previous versions of GeoBlacklight tied icons for each item based upon geometry type. We no longer have a comparable, single value field.  Do we want to bring back these icons in some form?

**Comment by ewlarson** [comment]
Ensure this works for Aardvark expections.

**Comment by karenmajewicz** [comment]
These have been implemented for Resource Class instead.
