### ISSUE TITLE
Move search button on homepage map

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/geoportal#367]
Consider moving the Search Here button from the bottom left to the top right of the map.

(This may affect other layout considerations)

**Comment by ewlarson** [comment]
Moving the button position is easy. Here's a picture of how that might look.

<img width="1273" alt="Screen Shot 2021-06-01 at 2 02 30 PM" src="https://user-images.githubusercontent.com/69827/120377554-e37dc500-c2e2-11eb-8196-8db1b73c2021.png">

However, I disagree with this UI change request. Every product homepage has a "Feng Shui". This change moves the map's search button into a position where it visually distracts from the homepage's primary collection access point: the application search form. The change breaks the "harmony" between these two collection entry options. The map and search are at peaceful truce in our current design and the "weight" of each access option needs to balance the other.

Hope that makes sense. Happy to chat more if you or the UI committee see it differently.

**Comment by karenmajewicz** [comment]
One thing we discussed was swapping the map and the Explore Maps and Data section. That might give more weight to the search form while also separating the Search options.

This would also match having a map on the right hand side on search results pages.

**Comment by ewlarson** [comment]
Here's a pic flipping the homepage main elements... I thought there was a reason they were map => text before, but I cannot recall. Let me know what you think.

<img width="1280" alt="Screen Shot 2021-06-01 at 4 46 52 PM" src="https://user-images.githubusercontent.com/69827/120394488-19c63f00-c2f9-11eb-914e-6f97e8c897fe.png">

**Comment by karenmajewicz** [comment]
Looks good to me. Having the main text search at the left might be easier to find.

The overall layout still has 2 Search buttons, but maybe they make more sense this way.

**Comment by ewlarson** [comment]
A little more polish on the homepage layout -- making the homepage headers and text all left-align correctly across all devices/breakpoints. Fixing the map's "Search here" button position.

Shall we go ahead and merge this into our main branch?

<img width="1280" alt="Screen Shot 2021-06-02 at 9 36 47 AM" src="https://user-images.githubusercontent.com/69827/120500176-44aaa480-c386-11eb-986e-66584046d655.png">

**Comment by karenmajewicz** [comment]
Yes, it seems worth giving it a go and seeing how we like it!
