### ISSUE TITLE
Adjust Item View fields

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/geoportal#369]
### Change labels:

- [x] Contributed by -> Provider
- [x] Type -> Resource Type

### Add as searchable values:
- [x] Resource Class
- [x] ISO Topic Category

### Add as plain text values:
- [x] Rights Holder
- [x] License (? - these are URIs; they could be clickable as external URL)
- [x] Format
- [x] File Size

**Comment by ewlarson** [comment]
I've added these fields to the Catalog#show page configuration. However! We don't have any fixtures in the project that include some of these fields: dcat_theme_sm, dct_rightsHolder_sm, dct_license_sm, gbl_fileSize_s

Can you think of a record that would include all of the above? Or, maybe we need a b1g fixture that just has placeholder values for all the fields we want to display there?

**Comment by ewlarson** [comment]
Closing via cd0a833
