### ISSUE TITLE
Update About page

### ISSUE THREAD

**Issue by KarenMajewicz** [BTAA-Geospatial-Data-Project/geoportal#37]
Add new institutions
For participant list at top, please add:

- Ohio State University
- University of Chicago

The updated map image is here:
![btaagdp-participantmap](https://user-images.githubusercontent.com/2367677/28475329-506b769c-6e11-11e7-9622-2212f7c02dda.png)

**Comment by RyanMattke** [comment]
Also, on the main page, change "Resources in the portal are selected and curated by librarians and geospatial specialists at ten research..." to "specialists at twelve research..."

**Comment by KarenMajewicz** [comment]
More Updates: https://docs.google.com/document/d/1a31-ytfK2Uwg27ErjsvcQpT428uxKkbPCII3fg17u_s/edit?usp=sharing

**Comment by ewlarson** [comment]
Okay!  Can you please help proof these updates?  If everything looks good, I'll release to production:
https://geodev.btaa.org/about

**Comment by KarenMajewicz** [comment]
There is a link for Bloomington Indiana I forgot: https://data.bloomington.in.gov/

**Comment by KarenMajewicz** [comment]
Wisconsin DNR link broken.  New one is here: http://dnr.wi.gov/maps/index.html

**Comment by KarenMajewicz** [comment]
Everything else looks good to me.

**Comment by ewlarson** [comment]
Moved to production
