### ISSUE TITLE
Review search relevancy algorithms

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/geoportal#370]

**Comment by ewlarson** [comment]
@karenmajewicz I think you know Aardvark best to lead this work. 

We'll want to add/remove fields from the relevancy scoring structure here:
https://github.com/BTAA-Geospatial-Data-Project/geoportal/blob/develop/solr/conf/solrconfig.xml#L116-L192

If we add any new Aardvark fields, like Resource Type or ISO Topic, we'll need to make copyfields for them here:
https://github.com/BTAA-Geospatial-Data-Project/geoportal/blob/develop/solr/conf/schema.xml#L182-L199

Maybe we should go through this together at tomorrow's meeting?

**Comment by ewlarson** [comment]
Add
- [ ] gbl_resourceType_tmi^6
- [ ] dcat_theme_sm^6
