### ISSUE TITLE
Update URI Analysis report with new fields

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/geoportal#371]
- [ ] For the column called "Collection" -> Retitle as Code and pull from `b1g_code_s`
- [ ] For the column called "Doc Data Type" -> Retitle as "Resource Class" and pull from `gbl_resourceClass_sm`

We don't really need the columns called State, URI ID, or B1G Status anymore since it only reports broken links.

**Comment by karenmajewicz** [comment]
note: did not receive a July report.

**Comment by ewlarson** [comment]
For the record, I did receive a July report. Are you still receiving mail sent to: geoportal@btaa.org?
