### ISSUE TITLE
Ideas for improving map on search results

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/geoportal#373]
I spent some time today looking for geospatial resources that cover a smaller town in Minnesota. The map was not very helpful. Here are some things I think that would make it better.

- [x] make the map much larger or create a full screen option
- [x] provide the option to switch base layers. The current base layer is not detailed enough at close zooms.  Maybe this plugin: https://leafletjs.com/examples/layers-control/
- [x] add the option to do a search by a place name powered by Google or other API. We have discussed this in the past with the concern that it would be too many search boxes. However, the functionality of the map is so diminished without it that I think it is essential. Consider how this integration works for MHAPO (https://apps.lib.umn.edu/mhapo/) or Princeton (https://maps.princeton.edu/). It's really hard to find locations without this kind of assistance, especially when the base layer for the map is not very detailed.  This plugin is what Princeton has: https://github.com/smeijer/leaflet-geosearch

**Comment by ewlarson** [comment]
Good feedback here.

1. A "full screen" option is likely best for now -- we're still "re-branding" someday, right?
2. Sure. Do you have a list of other base layers to configure?
3. Okay. Many of these Geo/Location APIs have usage restrictions or require a monthly subscription fee. Do you have a preference where we get this data? mhapo is using Esri and Princeton is using OSM.

**Comment by karenmajewicz** [comment]
3. These layers might be helpful to users:

- Open Street Map --  https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png
- Esri World Imagery -- https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}

**Comment by ewlarson** [comment]
Just a quick update here. I'm most of the way through this ticket. Here's where things stand:

<img width="1280" alt="Screen Shot 2021-07-07 at 5 24 25 PM" src="https://user-images.githubusercontent.com/69827/124836267-53b5e100-df48-11eb-9b97-ec9762e516af.png">

Here you can see the fullscreen option (the square one) , the basemap selector (top-right, onion skin thing), and the geosearch feature (the autosuggest) all on the homepage map. The basemap chosen is "sticky" across pages, as your selection is captured in a cookie.

It does introduce a lot of controls onto the map, but I agree all these features are quite useful. The position of these options is worth some discussion. I do not know if I can actually control all of the placement of these features.

**Comment by karenmajewicz** [comment]
This layout looks good and seems predictable compared to what other Leaflet maps do. Are the controls all displaying on the Search Results page as well? I can imagine that it would get crowded on a small map.

**Comment by ewlarson** [comment]
Yeah, they do appear on the search results page too. Here's some work to resize and move the basemap switcher. See bottom image for search results example.

<img width="1280" alt="Screen Shot 2021-07-08 at 8 31 55 AM" src="https://user-images.githubusercontent.com/69827/124930647-21979400-dfc7-11eb-83e1-9f7abc37fdec.png">

<img width="1280" alt="Screen Shot 2021-07-08 at 8 32 18 AM" src="https://user-images.githubusercontent.com/69827/124930663-252b1b00-dfc7-11eb-8af7-bd713a648570.png">

**Comment by ewlarson** [comment]
From WIP on geodev

- [ ] Fix WMS preview layer z-index
- [ ] Remove geosearch's default placename marker
