### ISSUE TITLE
Add a new line between multiple Description entries.

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/geoportal#374]
Multiple descriptions currently show up in the interface concatenated together without a space between the entries. Multiple description fields should be separated by at least a new line.

**Comment by ewlarson** [comment]
### Was:
<img width="766" alt="Screen Shot 2021-07-06 at 3 20 14 PM" src="https://user-images.githubusercontent.com/69827/124661867-b6867a00-de6d-11eb-8265-12d7dd88abaa.png">


### Now:
<img width="766" alt="Screen Shot 2021-07-06 at 3 18 27 PM" src="https://user-images.githubusercontent.com/69827/124661777-9787e800-de6d-11eb-8662-2ce1a895de3e.png">

**Comment by karenmajewicz** [comment]
Looks good! I took out the extra 'Canada' from the online record - good example of the ease of having GEOMG.
