### ISSUE TITLE
Add a Sort by Year (oldest first)

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/geoportal#375]
The results page includes a dropdown list that allows a user to sort by Relevance, Title, or Year. It does not specify in the interface, but the Year defaults to (newest first). Could another option be added for (oldest first)?

**Comment by ewlarson** [comment]
<img width="766" alt="Screen Shot 2021-07-06 at 1 18 15 PM" src="https://user-images.githubusercontent.com/69827/124648270-b16cff00-de5c-11eb-86df-0f797af55951.png">
