### ISSUE TITLE
Consider combining Creator/Publisher facet in search results page

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/geoportal#376]
User testing showed that the distinction between Creator and Publisher was unclear. Data providers and metadata authors also interpret these fields differently.

In the Advanced Search form, these fields appear to have been combined. Perhaps they could be combined in the search results facet as well? This would cut down on the number of facets as well as assist users in finding things by entity. They could still appear separately on the Item View page.

**Comment by ewlarson** [comment]
The advanced search form works differently from faceting. On the advanced search form, we're targeting our query against a solr request handler configuration that combines both the publisher and creator fields:
https://github.com/BTAA-Geospatial-Data-Project/geoportal/blob/develop/solr/conf/solrconfig.xml#L166-L173

It doesn't return a new combined facet of publisher + creator, it just searches both of those fields for hits. To combine those two fields into a single, facet-able bucket, we'd need to copyfield both publisher and creator values into a new field.

Hope that distinction is clear. This is definitely do-able, but this will require some work in GEOMG and Geoportal to get the job done.

**Comment by karenmajewicz** [comment]
See #385 for alternate plan.
