### ISSUE TITLE
When user clicks "Search Here" on the homepage map -> toggle Map View in Search Results

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/geoportal#377]
Users in our testing that used the homepage map wanted to continue using the map to refine results. They tried to use the back button to return to the homepage, but it reset to a world view.

I think this could be resolved by having the Map View toggled on when the homepage "Search Here" button is clicked.

**Comment by ewlarson** [comment]
Can do. We'll need to overwrite the default GBL geosearch.js module, to pass along the param for our "mapview" option:
https://github.com/geoblacklight/geoblacklight/blob/v3.3.1/app/assets/javascripts/geoblacklight/modules/geosearch.js#L103
