### ISSUE TITLE
Suppressed / Unpublished items are still findable via Google

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/geoportal#378]
[Example.](https://www.google.com/search?q=remonumented+section+corners+michigan&oq=remonumented+section+corners+michigan)

Has this always been the case or is it new behavior?  Google probably has a cache for retired items, but are items that were always suppressed findable as well?  Just need to clarify this.

**Comment by ewlarson** [comment]
Oops! That's a mistake. We need to update our sitemap.rb query to remove unpublished/suppressed items:
https://github.com/BTAA-Geospatial-Data-Project/geoportal/blob/develop/config/sitemap.rb#L4
