### ISSUE TITLE
Next Blog Post

### ISSUE THREAD

**Issue by KarenMajewicz** [BTAA-Geospatial-Data-Project/geoportal#38]
# Welcome to Ohio State University and the University of Chicago

This month, we welcomed two new Big Ten Academic Alliance universities to the project, Ohio State University and the University of Chicago.  Look for new collections from these contributors coming soon! Our updated map shows that we now represent a contiguous region from the Midwest to the Mid-Atlantic coast.

![btaagdp-participantmap](https://user-images.githubusercontent.com/2367677/28475541-51ab8cb2-6e12-11e7-90f6-c0a16c560e92.png)

# Collection Updates
## ArcGIS Open Data
Multiple collections from [ArcGIS Open Data portals](https://geo.btaa.org/?f%5Bdct_isPartOf_sm%5D%5B%5D=ArcGIS+Open+Data) were updated this month that included many new records from Michigan, Iowa, and Maryland. 

## Ramsey County, Minnesota
[Seven geodatabases from Ramsey County, Minnesota](https://geo.btaa.org/?f%5Bdct_isPartOf_sm%5D%5B%5D=Minnesota+Geospatial+Commons&f%5Bdct_spatial_sm%5D%5B%5D=Ramsey+County%2C+Minnesota%2C+United+States&page=1) containing dozens of feature classes were added this month.  This data can also be downloaded as shapefiles by visiting the [Minnesota Geospatial Commons](https://gisdata.mn.gov/organization/us-mn-co-ramsey) directly.

[![ramseycounty_parceldata](https://user-images.githubusercontent.com/2367677/28476102-5c923534-6e14-11e7-941c-e4eb703fe1fc.png)](https://geo.btaa.org/catalog/50ed2ceb-38c0-480c-933f-82a2b332bae4)

**Comment by ewlarson** [comment]
Pushed to production.
