### ISSUE TITLE
Change item view page dct_rights_sm label

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/geoportal#383]
The label on the item page currently has the legacy "Access Rights." This confuses it with the new dct_accessRights_s field. Can we change the label to say just "Rights"?

Here is an example: https://geo.btaa.org/catalog/d6684a2a-f3e1-4492-8b5d-b399bf4f6553

**Comment by ewlarson** [comment]
Closing via https://github.com/BTAA-Geospatial-Data-Project/geoportal/pull/384
