### ISSUE TITLE
Download button no longer working

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/geoportal#398]
I haven't tracked down what caused this yet, but when a user clicks the "Download" button, the page just refreshes.

**Comment by karenmajewicz** [comment]
Maybe this file (https://github.com/BTAA-Geospatial-Data-Project/geoportal/blob/develop/config/locales/geoblacklight.en.yml) which shows:

> en:
  geoblacklight:
    bbox_label: 'Bounding Box'
    download:
      download: 'Download'
      download_link: 'Original %{download_format}'

Maybe we removed `download_format`as a variable during the updates.

**Comment by mberkowski** [comment]
I'll look at the logs when I get a chance later today

**Comment by karenmajewicz** [comment]
Rolling back is fine!  Thanks, @mberkowski - That will also give us more flexibility to work on it next month, so Eric doesn't have to tackle it right way.

**Comment by karenmajewicz** [comment]
Downloads are working again! Thank you!
