### ISSUE TITLE
Determine preferred Year sorting behavior for items missing gbl_indexYear_im

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/geoportal#399]
Some items in the geoportal do not have a value for `gbl_indexYear_im`. When using the sort by Year (oldest) function, these items are floating to the top. 

Perhaps these items could instead be relegated to the bottom for this kind of sort? Or, is there a better solution?

**Comment by karenmajewicz** [comment]
Upgrading the priority on this issue:

- project members tested the date sorting feature at a recent sprint and the results were not helpful
- as we update metadata, we are increasingly leaving Date Range & Index Year blank, as public geodata is regularly getting updated and our dates become inaccurate. 
- items with null values for Date Range render the date sort feature hard to use

**Comment by ewlarson** [comment]
https://solr.apache.org/guide/6_6/field-type-definitions-and-properties.html#field-type-properties
Will give `sortMissingLast="true"` a try...
