### ISSUE TITLE
Migrate BTAA Geoportal to AWS alongside GEOMG

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/geoportal#409]
This has been our longer term plan anyway. I am proposing that it be fast-tracked to happen sooner. Two things to note about the current setup:

- Solr searches in the geoportal have been running very slowly for the past 2 months - (I've gotten unsolicited feedback from several project members affirming this.)  
- The lag time between uploading/editing records in GEOMG and changes in Solr is negatively affecting the efficiency of metadata work.

**Comment by mberkowski** [comment]
I'm working on this move. The hardest thing is coordinating with UIUC the btaa.geo.org domain name pointing to a different IP.
About Solr, we have seen a few times especially in the last week and a half where we get coinciding crawls by multiple outside groups which are dragging on Solr. The OIT VM is really underpowered so yes it has to move.

**Comment by karenmajewicz** [comment]
Thanks for the update! Let me know if there is any way to help out with the domain name coordinating.
