### ISSUE TITLE
Generated GeoServer exports are not working

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/geoportal#418]
Here is an example: https://geo.btaa.org/catalog/harvard-tg95coaircupy

When selecting one of the generated exports (shapefile, KMZ, or geojson), the application does not appear to do anything. The console shows `/download/harvard-tg95coaircupy?type=shapefile:1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)`

For reference, this record does export and download in Princeton's geoportal (https://maps.princeton.edu/catalog/harvard-tg95coaircupy). 

I am not sure when the bug appeared, as we don't have many GeoServer records in the Geoportal and I just added several hundred last week.

**Comment by ewlarson** [comment]
Okay... Fixed this in production by adding a "downloads" directory to the `#{Rails.root}/tmp/cache` folder -- GBL needs that downloads tmp directory present to be able to write tempfiles into it.

No commit here. Just added the dir to the production environment.

**Comment by ewlarson** [comment]
^ Made the same update to our development box too.

**Comment by mberkowski** [comment]
Some of the rails tmp dirs get pre-created by ansible. I'll add tmp/cache/downloads to that list.

**Comment by mberkowski** [comment]
I lied it's capistrano that drills in and does `mkdir -p` on tmp/cache so I extended that to downloads/

**Comment by karenmajewicz** [comment]
The behavior on these pages is still odd for me. I was able to generate a KMZ for download, but requesting a shapefile or geojson consistently returns the error `Sorry, the requested file could not be downloaded. Try downloading it directly from: https://geodata-proxy.lib.harvard.edu/geoserver/proxy/requestfile/wfs`

**Comment by ewlarson** [comment]
Hmmm... I'm seeing consistent 504s returned (Gateway Timeout server error response) when trying to touch that Harvard server. I don't think this is a bug in our codebase, but rather a bad day for Harvard or they're rate limiting us.
