### ISSUE TITLE
Replace fixture docs in Develop branch with Aardvark versions

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/geoportal#449]

**Comment by karenmajewicz** [comment]
Oh, wait, I see we have both. Is this needed?

**Comment by ewlarson** [comment]
Should be done already:
https://github.com/BTAA-Geospatial-Data-Project/geoportal/tree/develop/test/fixtures/files

**Comment by karenmajewicz** [comment]
Thanks. Is the /spec directory no longer used?

**Comment by ewlarson** [comment]
Correct! That dir is no longer necessary, we should 86 it.
