### ISSUE TITLE
Geometry/BBoxes are not being published from new records

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/geoportal#454]
What should happen:

1. A new record is created/imported into GEOMG with a Bounding Box value
2. This value gets copied into both `dcat_bbox` and `locn_geometry`
3. A `dcat_centroid` is generated
4. The record displays with a bounding box in the Geoportal

What is happening:
1. A new record in created/imported into GEOMG with a Bounding Box value
2. A `dcat_centroid` is generated
3. The record does not have either a `dcat_bbox` nor a `locn_geometry` field in the geoportal

-----
In the last sprint, existing records were migrated to the new schema fine. It is only new records that are not getting geometry values.

**Comment by karenmajewicz** [comment]
I am unsure of what is happening with dcat_centroid though.

I just published this record and a centroid was generated (no geometry, though) https://geo.btaa.org/catalog/ark-85335-m5td9q45t/admin

However, I just created this test record, and although there is a bbox in GEOMG, there is no centroid in the interface: https://geo.btaa.org/catalog/test-bbox/admin

**Comment by ewlarson** [comment]
Will take a look today 👀

**Comment by ewlarson** [comment]
Closing via GEOMG v0.12.1 release:
https://github.com/BTAA-Geospatial-Data-Project/geomg/releases/tag/0.12.1
