### ISSUE TITLE
Determine if HTML metadata view not compatible with XMLs on FTP sites

### ISSUE THREAD

**Issue by KarenMajewicz** [BTAA-Geospatial-Data-Project/geoportal#48]
Some FGDC XML metadata files are throwing errors.  It is only the ones hosted on ftp, so this seems likely to be the problem.  

Works OK: https://geodev.btaa.org/catalog/0f3c5f91-37dc-4557-9606-9658ae45a4c8
Produces Error when metadata button is clicked: https://geodev.btaa.org/catalog/7c265045-bd32-4392-95c9-616e4d760298

**Comment by ewlarson** [comment]
GeoBlacklight's metadata code is HTTP only.  It does not speak FTP natively.  I pinged the original developer of this feature, but haven't heard back yet:
https://github.com/geoblacklight/geoblacklight/issues/559

**Comment by KarenMajewicz** [comment]
Moved FTP records to our server at btaagdp.org/metadata

**Comment by KarenMajewicz** [comment]
Closing since metadata hosted on FTP will be moved to project server or GitHUB
