### ISSUE TITLE
Blog Post for September

### ISSUE THREAD

**Issue by KarenMajewicz** [BTAA-Geospatial-Data-Project/geoportal#49]
# New features!

As of September 2017, the BTAA Geoportal has three new features: 

## Enhanced Metadata Display
Many records include the text “metadata” in the right hand toolbox.  Clicking this item will bring up an HTML view of geospatial metadata in either the FGDC or ISO19139 standard.

![metadatabutton](https://user-images.githubusercontent.com/2367677/30349342-558f79d4-97d8-11e7-832f-f62612d3c2c9.png)
![metadataview](https://user-images.githubusercontent.com/2367677/30349355-5b53faf2-97d8-11e7-8c4e-ab80c802ef58.png)

## Browse for Items on the Map
The map on the homepage now displays a center point for each record in the geoportal.  Users can zoom into clustered markers to see more detail and select single points to go directly to the item’s landing page.
![mapsearch](https://user-images.githubusercontent.com/2367677/30349373-6a169ed2-97d8-11e7-9649-6ade2ce32527.png)

## Autocomplete for the Search box
When typing text into the Search box, the geoportal will dynamically show matching keywords. For example, typing _bi_ into the Search box returns a dropdown list of terms containing that string, such as _biota_, _biology_, and _biogeography_.
![biota](https://user-images.githubusercontent.com/2367677/31180633-bb94a3f4-a8e4-11e7-87f8-65e302cbee99.png)

**Comment by KarenMajewicz** [comment]
"bump"

**Comment by ewlarson** [comment]
Sorry! This slipped through my inbox. I'll be in the office tomorrow and
will post it immediately.

**Comment by ewlarson** [comment]
This blog post is up for review now: https://geodev.btaa.org/blog/2017/09/12/new-features.html

The last image looks a bit odd to me, with all the browser tabs and the desktop icons in the background. If you feel like changing it let me know, otherwise let me know if this is ready to be pushed live.

**Comment by KarenMajewicz** [comment]
Oh, I forgot to crop it!  Thanks for noticing.  I replaced it.

**Comment by KarenMajewicz** [comment]
Thanks- looks good on dev.
