### ISSUE TITLE
Enable bounding box inset to display when a scanned map is part of the item page.

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/geoportal#62]

**Comment by KarenMajewicz** [comment]
Could this be used for resources without a web service or static image?  This might improve consistency and avoid the problem of users thinking the basemap under the bounding box is the resource itself.

If so, the name of the inset should probably be changed from "Map Area" to something more general, like "Bounding Box", "Geographic Extent", or "Location"

Something like this mockup:
![mockup](https://user-images.githubusercontent.com/2367677/41320892-3a14c5ae-6e67-11e8-81fe-88abe6b11c0b.jpg)
