### ISSUE TITLE
Enable MosaicRule for Esri ImageServer

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/geoportal#64]
Purdue has georeferenced old campus maps and published them as mosaic datasets on an ArcGIS Image Server at this address: https://mapsweb.lib.purdue.edu/arcgis/rest/services/Purdue/campus_history/ImageServer

Individual maps/sections can be isolated with a query, such as this: https://mapsweb.lib.purdue.edu/arcgis/rest/services/Purdue/campus_history/ImageServer/exportImage?mosaicRule=%7B%22mosaicMethod%22%3A%22esriMosaicLockRaster%22%2C%0D%0A%22lockRasterIds%22%3A+%5B1%5D%7D

GeoBlacklight’s web service preview box does support ArcGIS Image Servers.  👍
However, it does not work with a mosaic query. 👎

Here is some documentation on getting a MosaicRule to show up on Leaflet: https://esri.github.io/esri-leaflet/examples/image-map-layer-mosaic-rule.html

**Comment by jgravois** [comment]
> GeoBlacklight’s web service preview box does not work with a mosaic query. 👎

why exactly is that? is there something missing in esri-leaflet that you'd need?

**Comment by karenmajewicz** [comment]
Add example fixtures to test this

**Comment by karenmajewicz** [comment]
I have not seen other web services that are mosaicked like this. Closing from lack of need.
