### ISSUE TITLE
Change Data Relations Tool terminology or create parent/child relationship

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/geoportal#65]

**Comment by karenmajewicz** [comment]
The plugin is useful, but the terms do not match our usage. Suggested change:

Data Relations -> Relations

Source Datasets -> Parent Record
Derived Datasets -> ?

**Comment by ewlarson** [comment]
How does this look?
https://geodev.btaa.org/catalog/88cc9b19-3294-4da9-9edd-775c81fb1c59

Data Relations -> Relations
Source Datasets -> Parent Record
Derived Datasets -> Related Records

**Comment by karenmajewicz** [comment]
I think this terminology is perfect. One thing I noticed is that the Browse all 25 Records link is broken now…


I am still reviewing the other 1.9 changes and will get back to you with any issues I find.




Karen Majewicz
Geospatial Project Metadata Coordinator

John R. Borchert Map Library, University of Minnesota Libraries
Room s98

**Comment by ewlarson** [comment]
It's odd that link is now broken. I'll open an issue for that.
