### ISSUE TITLE
Add support for thumbnails hosted on ftp

### ISSUE THREAD

**Issue by KarenMajewicz** [BTAA-Geospatial-Data-Project/geoportal#66]
Example: https://geodev.btaa.org/?utf8=%E2%9C%93&search_field=all_fields&q=Total+Maximum+Daily+Load+%28TMDL%29+and+Watershed+Restoration+and+Protection+Strategy+%28WRAPS%29+Project+Boundaries%3A+Minnesota

**Comment by ewlarson** [comment]
We'll need to download and re-host these images. FTP just isn't a way to present images online.

**Comment by KarenMajewicz** [comment]
Haha, tell that to a quarter of all the county and state GIS offices out there! 
I'll add this to the "rejected" column.

**Comment by ewlarson** [comment]
FTP is a good protocol to share files, but you can't load that content via the FTP protocol in an image tag in any modern browser. 

Disk space is cheap. We can likely re-host these assets, unless you're concerned about what all that might entail. It would certainly add up... but I don't get the sense we'll ever grow wildly big.

**Comment by KarenMajewicz** [comment]
Hosting thumbnails ourselves is a promising idea and would improve how quickly they show up in the search results.  But, it would add labor to our workflow, so I'll have to review it with the Steering Grp.

**Comment by KarenMajewicz** [comment]
Closing - need different solution
