### ISSUE TITLE
Deprecate UUID and use layer_slug_s

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/geoportal#69]
This field has been deprecated in GBL Metadata 1.0 schema.  As a result, we are unable to ingest records from other schools that do not include a UUID field.  This value is already duplicated in our schema in dc_identifier_s and layer_slug_s.  To match the other institution's metadata, we should use layer_slug_s as the key.

**Comment by ewlarson** [comment]
If we abandon our UUID identifiers, all of the links to items in the Geoportal will be broken. Let's chat about this today when we meet.

**Comment by KarenMajewicz** [comment]
dc_identifier_s is a duplicate element and holds the same alphanumeric ID as UUID.

**Comment by KarenMajewicz** [comment]
There is also layer_slug_s, which has the same value as UUID and dc_identifier_s.  Doesn't the slug element control the URL?

**Comment by ewlarson** [comment]
In production with release 1.8.12
