### ISSUE TITLE
Institution facet issue

### ISSUE THREAD

**Issue by ewlarson** [BTAA-Geospatial-Data-Project/geoportal#7]
Actually... our issue stems from the icon_facet partial rendering those facet values. That partial does not include the necessary logic to present a "more" link. It just stops rendering facet values when the configured facet limit is reached.

Here's the partial with the missing logic (Geoblacklight v0.12.1):
https://github.com/geoblacklight/geoblacklight/blob/9f2d1e918aba4cc6f34b1435c8474da2dc238121/app/views/catalog/_icon_facet.html.erb

Here's an example of the "more_facets_link" logic that should be included (Blacklight 5.18.0):
https://github.com/projectblacklight/blacklight/blob/f17d23d585c50a81f3a8c9666cb5ff99beeed579/app/views/catalog/_facet_limit.html.erb

It's worth noting, if you perform an empty search on Earthworks, they have this bug, too:
https://earthworks.stanford.edu/?utf8=%E2%9C%93&q=

For now, I'm going to remove our use of the icon_facet partial, until a fix can be submitted to geoblacklight.

**Comment by ewlarson** [comment]
Same problem here: https://github.com/geoblacklight/geoblacklight/issues/587

**Comment by KarenMajewicz** [comment]
fixed as of version 1.7.1 https://github.com/geoblacklight/geoblacklight/releases/tag/v1.7.1
