### ISSUE TITLE
Dec 2017 Blog Post

### ISSUE THREAD

**Issue by KarenMajewicz** [BTAA-Geospatial-Data-Project/geoportal#72]
# New GIS & Scanned Map Records: Fall 2017

## Indiana Historic Maps
This collection includes over 300 public domain maps from the University of Indiana Library spanning the early 1800s to the late 20th century. Many depict the entire state of Indiana, but there are also city maps, including [Gary](https://geo.btaa.org/?_=1513006073854&f%5Bdct_isPartOf_sm%5D%5B%5D=Indiana+Historic+Maps&f%5Bdct_spatial_sm%5D%5B%5D=Gary%2C+Indiana%2C+United+States&per_page=20&search_field=all_fields), [Bloomington](https://geo.btaa.org/?_=1513006008801&f%5Bdct_isPartOf_sm%5D%5B%5D=Indiana+Historic+Maps&f%5Bdct_spatial_sm%5D%5B%5D=Bloomington%2C+Indiana%2C+United+States&per_page=20&search_field=all_fields), [Indianapolis](https://geo.btaa.org/?_=1513006008801&f%5Bdct_isPartOf_sm%5D%5B%5D=Indiana+Historic+Maps&f%5Bdct_spatial_sm%5D%5B%5D=Indianapolis%2C+Indiana%2C+United+States&per_page=20&search_field=all_fields), and others. 
![indiana](https://user-images.githubusercontent.com/2367677/33839069-e41e2c58-de56-11e7-8939-cebb4c9c3834.jpeg)
_[Indiana, 1950: age-sex pyramids for counties excluding places over 10,000 in 1940](https://geo.btaa.org/catalog/ed6576a8-778d-4fc9-a101-bff8d7c7ae8a)_

## Cook County, Illinois GIS Data
127 new [GIS dataset administrative records have been added from Cook County, Illinois](https://geo.btaa.org/?_=1513007254369&f%5Bdct_isPartOf_sm%5D%5B%5D=Cook+County+Open+Data), which encompasses the city of Chicago.
![cookcountygisdata](https://user-images.githubusercontent.com/2367677/33839694-8fe3786c-de58-11e7-8d2a-9b00d4e0e1f9.png)

## Wisconsin and Minnesota Counties
More and more counties are providing their GIS data through open data portals and [220 items were added from Wisconsin counties](https://geo.btaa.org/?_=1513006803142&f%5Bdct_isPartOf_sm%5D%5B%5D=Wisconsin+Counties+Open+Data&search_field=all_fields&sort=dc_publisher_sort+asc%2C+dc_title_sort+asc), as well as from the Minnesota counties of [Hubbard](https://geo.btaa.org/?_=1513006989433&f%5Bdct_isPartOf_sm%5D%5B%5D=ArcGIS+Open+Data&f%5Bdct_spatial_sm%5D%5B%5D=Hubbard+County%2C+Minnesota%2C+United+States&search_field=all_fields&sort=dc_publisher_sort+asc%2C+dc_title_sort+asc) and [Carlton](https://geo.btaa.org/?_=1513006989433&f%5Bdct_isPartOf_sm%5D%5B%5D=ArcGIS+Open+Data&f%5Bdct_spatial_sm%5D%5B%5D=Carlton+County%2C+Minnesota%2C+United+States&search_field=all_fields&sort=dc_publisher_sort+asc%2C+dc_title_sort+asc).
![hubbardcounty](https://user-images.githubusercontent.com/2367677/33839923-19e2d5e4-de59-11e7-9013-8b81c963c186.png)
_[Roads: Hubbard County, Minnesota](https://geo.btaa.org/catalog/364ddc8c3277441e8355698034b9b968_0)_

**Comment by ewlarson** [comment]
Already published.
