### ISSUE TITLE
IIIF causing external server issues?

### ISSUE THREAD

**Issue by KarenMajewicz** [BTAA-Geospatial-Data-Project/geoportal#73]
While browsing [this collection](https://geodev.btaa.org/?f%5Bdct_isPartOf_sm%5D%5B%5D=Clark+Library+Map+Collections&f%5Blayer_geom_type_s%5D%5B%5D=Paper+Map&page=1&search_field=all_fields) on the dev site, I opened [this record. ](https://geodev.btaa.org/catalog/f395de7b-7a57-47b3-8613-9e603650fbaa) When I clicked on the "more details at" link, I got this error:

https://quod.lib.umich.edu/ErrorDocument509.html
![um509](https://user-images.githubusercontent.com/2367677/33849464-46fc1726-de76-11e7-8aa5-ad9512e2e917.png)

**Comment by KarenMajewicz** [comment]
After this, the thumbnails are not showing up in browse and the IIIF is empty.

**Comment by ewlarson** [comment]
Looks like they throttle content to 1 request/sec. If you're a quick clicker, you'll see the error page. We should investigate this a little more and contact UMDL to chat things over a bit.

This is a good example why self-hosting a IIIF solution for the B1G Geoportal would benefit even the institutions that have IIIF availability on their campuses.

**Comment by KarenMajewicz** [comment]
Another detail - this occurs when I the [search results page is set to 100. ](https://geodev.btaa.org/?f%5Bdct_isPartOf_sm%5D%5B%5D=Clark+Library+Map+Collections&per_page=100&q=&search_field=all_fields) By the 4th page, they stop loading. (regardless of click speed)

**Comment by respinos** [comment]
Wouldn't B1G Geoportal have to host all the media if you want to avoid throttling issues --- I tried to work around the issue for you on the back-end, but Leaflet-IIIF doesn't budge from the initial URL. Still working on it.

**Comment by ewlarson** [comment]
There are lots of options here, but first I'd contact Michigan to talk to the people running their IIIF server. They might geo* to pull data beyond the throttling threshold.

Still, throttling is just one issue of having external assets. The best option would always be hosting assets locally for ourselves.

**Comment by respinos** [comment]
(Sorry, that is me asking in role of Michigan person :-)

**Comment by ewlarson** [comment]
@respinos Sorry! Thought you were Karen. Nice to see other people here.

**Comment by KarenMajewicz** [comment]
So, I think the problem might be just resulting from trying to use the thumbnails.  We are experimenting with embedding thumbnails from IIIF to display on search results pages.  This means that many calls are happening at once.  The format we are using for the thumbnail links is like so: https://quod.lib.umich.edu/cgi/i/image/api/image/clark1ic:003286864:39015091197825/full/res:5/0/native.jpg?attachment=1

**Comment by KarenMajewicz** [comment]
Perhaps we could harvest all of the the thumbnails and host them ourselves?  They are small files, but there are 802 of them.

[CSV of UUIDs + thumbnail links](https://docs.google.com/spreadsheets/d/1Snb294cgvMh8u97vqOUNAqHFKtGxw5saro2UPlv2eCM/edit?usp=sharing)

**Comment by KarenMajewicz** [comment]
Resolved with new thumbnail code
