### ISSUE TITLE
Fix text encoding issues on search results page of dev site

### ISSUE THREAD

**Issue by KarenMajewicz** [BTAA-Geospatial-Data-Project/geoportal#74]
The search results page of dev site is showing certain characters like ampersands and apostrophes as codes.

Example: Dev
![dev](https://user-images.githubusercontent.com/2367677/34063581-8cf7050c-e1b8-11e7-8aaf-b3d16b962b73.png)

Compare: Prod
![prod](https://user-images.githubusercontent.com/2367677/34063586-930a6de4-e1b8-11e7-90d8-868fdfd97381.png)

**Comment by ewlarson** [comment]
1.7.0 update appears to address this issue.

**Comment by ewlarson** [comment]
Fixed with the 1.7.0 release
