### ISSUE TITLE
Add a loading GIF for web services

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/geoportal#76]
Many of these web services are slow to load and users are not able to determine if something is happening.

**Comment by ewlarson** [comment]
The simple technique here could work: http://bl.ocks.org/rgdonohue/d249d65397d02f5cf0d6

**Comment by karenmajewicz** [comment]
Add fixture to test

**Comment by karenmajewicz** [comment]
using "data loading" button

**Comment by ewlarson** [comment]
Added an animated fade for the "Data Loading" badge.

![data_loading](https://user-images.githubusercontent.com/69827/67589171-7b85f680-f71d-11e9-9176-06fb25e832be.gif)
