### ISSUE TITLE
Investigate issues with scale settings for web services

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/geoportal#78]
When web services are set to a large scale minimum, they do not appear in the preview box unless a user knows to zoom way in.  Example: https://geodev.btaa.org/catalog/B883C9B9-0D43-4B78-BDF0-B7F1B520C4F2

The minimum scale for this is set at 200000, but the extent is the full state of Wisconsin.

**Comment by ewlarson** [comment]
Closing. Out of scope.
