### ISSUE TITLE
Re-map icon for "Vector" geometry type

### ISSUE THREAD

**Issue by KarenMajewicz** [BTAA-Geospatial-Data-Project/geoportal#82]
The specific geometry type (polygon, point, etc.) is not available through metadata harvested via DCAT or APIs. Items that must be re-accessioned every month cannot be inspected individually for timely processing, so are being assigned "Vector" or "Raster."  Vector does not have an icon associated with it in the GBL application.  

Another possibility is to fix GBL so that geometry type is no longer needed to load records into Solr. ([GeoBlacklight issue #516](https://github.com/geoblacklight/geoblacklight/issues/516)

**Comment by KarenMajewicz** [comment]
map to multipolygon.svg

**Comment by ewlarson** [comment]
Included in the 1.7.0 release.
