### ISSUE TITLE
Determine issue with flipped bounding boxes

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/geoportal#84]
The bounding boxes for many items display horizontally flipped.  This is usually when the eastern and western extents cross the [180th meridian](https://en.wikipedia.org/wiki/180th_meridian) / International Date Line.  The most common problem records have been for scanned maps depicting Asia that show up as depicting North America.

Examples:
[The North Coast of Russia, from the Latest Discoveries](https://geo.btaa.org/catalog/dcca0fd9-ddda-4348-8d41-e7194e2b665f)
[Asiae nova descriptio](https://geo.btaa.org/?utf8=%E2%9C%93&search_field=all_fields&q=Asiae+nova+descriptio)

**Comment by KarenMajewicz** [comment]
Asiae nova descriptio that displays flipped (https://geo.btaa.org/catalog/712f1fa9-2bea-43c2-987f-aea86440f48f):
W35.33203125, E-170.859375

Asiae nova descriptio that displays correctly (https://geo.btaa.org/catalog/b2c6fcf9-0240-4eec-836c-893af3cb8339):
W25.01, E146.31

**Comment by KarenMajewicz** [comment]
The flipped record still displays the same if the W and E coordinates are reversed in the metadata record: https://geodev.btaa.org/?utf8=%E2%9C%93&search_field=all_fields&q=Asiae+nova+descriptio
W-170.859375, E35.33203125

**Comment by karenmajewicz** [comment]
This has been addressed in the latest version of GeoBlacklight. Further work on refining the solution will happen there.
