### ISSUE TITLE
Update the Sources section on the About page

### ISSUE THREAD

**Issue by KarenMajewicz** [BTAA-Geospatial-Data-Project/geoportal#89]
## Statewide
[Illinois Geospatial Data Clearinghouse](https://clearinghouse.isgs.illinois.edu/data)
[IndianaMAP](http://maps.indiana.edu/layerGallery.html)
[Iowa Geodata](https://geodata.iowa.gov)
[IowaDOT](http://public.iowadot.opendata.arcgis.com)
[Maryland iMap](http://data.imap.maryland.gov)
[Minnesota Geospatial Commons](https://gisdata.mn.gov/)
[Minnesota Legislative Coordinating Commission - Geospatial Information (LCC-GIS)](https://www.gis.leg.mn/html/download.html)
[Ohio Department of Natural Resources](http://ogrip-geohio.opendata.arcgis.com)
[Pennsylvania Spatial Data Access, PASDA](http://www.pasda.psu.edu/)
[State of Michigan Open Data Portal](http://gis-michigan.opendata.arcgis.com)
[State of Wisconsin](http://maps.sco.wisc.edu/opengeoportal/)
[Wisconsin Department of Agriculture, Trade, and Consumer Protection (DATCP)](http://maps.sco.wisc.edu/opengeoportal/)
[Wisconsin Department of Natural Resources (DNR)](http://maps.sco.wisc.edu/opengeoportal/)
[Wisconsin Imagery/LiDAR](http://maps.sco.wisc.edu/opengeoportal/)
[Wisconsin Legislative Technology Services (LTSB)](http://maps.sco.wisc.edu/opengeoportal/)

## Regional
[Delaware Valley Open Data](https://dvrpc-dvrpcgis.opendata.arcgis.com/)
[SEMCOG, the Southeast Michigan Council of Governments](http://maps-semcog.opendata.arcgis.com)

### Illinois
[City of Chicago Data Portal](https://data.cityofchicago.org/)
[Cook County Open Data](https://datacatalog.cookcountyil.gov/)
### Indiana
[Bloomington Open Data](https://data.bloomington.in.gov)
[Indianapolis Open Data](http://data1-indygis.opendata.arcgis.com)
[South Bend Open Data](http://data-southbend.opendata.arcgis.com)

### Maryland
[District of Columbia Open Data](http://opendata.dc.gov)
[Baltimore Open Data](http://gis-baltimore.opendata.arcgis.com)
[Open Baltimore](https://data.baltimorecity.gov)

### Michigan
[City of Ann Arbor](https://www.a2gov.org/services/data/Pages/default.aspx)
[Detroit Open Data](https://data.detroitmi.gov)
[Oakland County Open data](http://accessoakland.oakgov.com)

### Minnesota
[Anoka County](https://www.anokacounty.us/1990/Data-Downloads)
[Becker County](http://www.co.becker.mn.us/online_services/GIS_data.aspx)
[Carver County](http://data-carver.opendata.arcgis.com)
[Chisago County](http://gis.chisagocounty.us/Link/jsfe/index.aspx)
[Clay County](http://claycountymn.gov/658/GIS-Data)
[Hennepin County](http://gis-hennepin.opendata.arcgis.com)
[Minneapolis Open Data](http://opendata.minneapolismn.gov)
[Otter Tail County](http://www.co.otter-tail.mn.us/DocumentCenter)
[St Louis County](http://stlouiscountymndata-slcgis.opendata.arcgis.com)
[Scott County](http://opendata.gis.co.scott.mn.us)
[Stearns County](https://co.stearns.mn.us/PropertyRoads/GISDataforDownload)
[Washington County](http://data-wcmn.opendata.arcgis.com)
[Carlton County](http://data-carltoncounty.opendata.arcgis.com)
[Hubbard County](https://getdata-hubbardcounty.opendata.arcgis.com)

### Wisconsin
Counties with open data catalogued at geodata@wisc.edu:
Adams, Ashland, Barron, Bayfield, Brown, Buffalo, Burnett, Calumet, Chippewa, Clark, Columbia, Crawford, Dane, Dodge, Door, Douglas, Dunn, Eau Claire, Florence Country, Florence, Fond du Lac, Forest, Grant, Green, Green Lake, Iowa, Iron, Jackson, Jefferson, Juneau, Kenosha, Kewaunee, La Crosse, Lafayette, Langlade, Lincoln, Manitowoc, Marathon, Marinette, Marquette, Menominee, Milwaukee, Monroe, Oconto, Oneida, Outagamie, Ozaukee, Pepin, Pierce, Polk, Portage, Price, Racine, Richland, Roads Taylor, Rock, Rusk, Sauk, Sawyer, Shawano, Sheboygan, St. Croix, Taylor, Trempealeau, Vernon, Vilas, Walworth, Washburn, Washington, Waukesha, Waupaca, Waushara, Winnebago, Wood

## University Libraries and Repositories
[Clark Library Scanned Maps, University of Michigan](https://quod.lib.umich.edu/c/clark1ic?page=index)
[Data Repository for the U OF M (DRUM)](https://conservancy.umn.edu/handle/11299/166578)
[Hixson Plat Map Atlases of Iowa](http://digital.lib.uiowa.edu/cdm/landingpage/collection/hixson)
[Indiana Historic Maps](http://webapp1.dlib.indiana.edu/images/splash.htm?scope=IUBMaps)
[Iowa Historical County Atlases](http://digital.lib.uiowa.edu/cdm/landingpage/collection/atlases)
[John R. Borchert Map Library](http://umedia.lib.umn.edu/)
[Michigan State University Libraries Maps](https://lib.msu.edu/branches/map/scannedmaps/intro/)
[Minnesota Geological Survey County Atlas Series](https://conservancy.umn.edu/)
[Minnesota Geological Survey Maps](https://reflections.mndigital.org/?f%5Bcollection_name_ssi%5D%5B%5D=Minnesota+Geological+Survey&f%5Bphysical_format_ssi%5D%5B%5D=Maps)
[Pennsylvania State University Rare Maps](https://libraries.psu.edu/about/collections/digital-map-drawer)
[Polar Geospatial Center at the University of Minnesota](http://maps.apps.pgc.umn.edu/)
[Purdue Georeferenced Imagery](https://mapsweb.lib.purdue.edu/arcgis/rest/services/Purdue/campus_history/ImageServer/)
[Sanborn Maps from Pennsylvania State University](https://libraries.psu.edu/about/collections/sanborn-fire-insurance-maps)
[University of Maryland Digital Collections](https://www.lib.umd.edu/mdmap/?pid=umd:57340)

**Comment by ewlarson** [comment]
Just checking... but shouldn't these be bulleted lists? (I think yes)

**Comment by KarenMajewicz** [comment]
Sure, the bullets seem to make it more legible.  Thanks!

**Comment by ewlarson** [comment]
Deployed to production with 1.8.2 release.

**Comment by KarenMajewicz** [comment]
The whole Wisconsin Counties section near the bottom should be changed to this:

### Wisconsin
Publicly available state and local data layers for all 72 Wisconsin counties can be directly downloaded from [GeoData@Wisconsin](http://geodata.wisc.edu/opengeoportal/).
