### ISSUE TITLE
Make ExceptionNotifier ignore local crawler

### ISSUE THREAD

**Issue by mberkowski** [BTAA-Geospatial-Data-Project/geoportal#91]
Qualys hits us too hard every Thursday morning.

https://makandracards.com/makandra/17469-exception_notification-4-0-0+-makes-it-easier-to-ignore-errors-crawlers

See existing email notices for examples of the REMOTE_ADDR we would want to ignore if we can't just ignore all crawlers.

**Comment by mberkowski** [comment]
Fixed by #92

**Comment by ewlarson** [comment]
Deployed to production with 1.8.2 release.
