### ISSUE TITLE
Create page level feedback option for users to report issues/problems

### ISSUE THREAD

**Issue by KarenMajewicz** [BTAA-Geospatial-Data-Project/geoportal#95]

**Comment by ewlarson** [comment]
What email address(es) should receive feedback messages? I'll include my own (ewlarson@umn.edu), but who else might want a copy?

**Comment by ewlarson** [comment]
My feature/FeedbackForm branch contains working code for the feedback form. @mberkowski will add the reCaptcha API keys to our ansible playbook, so these secrets are available to the application.

Let me know what you think of layout/design/etc. Screenshot below:

![screen shot 2018-06-27 at 2 39 01 pm](https://user-images.githubusercontent.com/69827/41996452-906246f2-7a1a-11e8-9176-94d074fa63eb.png)

**Comment by KarenMajewicz** [comment]
Looks very nice!  Did you have Topics in mind?

**Comment by ewlarson** [comment]
The available topics are just the checkbox options from the current contact us form.

**Comment by KarenMajewicz** [comment]
- Correction
- Question
- Comments or Suggestions
- Other

Seems good to me.
